/* Generated by scripts/build-public.mjs — 0.7.0-alpha.11 */
const CACHE_NAME="studo-shell-0.7.0-alpha.11";
const APP_SHELL=["index.html","offline.html","404.html","favicon.svg","assets/chee-skool-logo.png","manifest.json","css/site.css","js/app.js","js/storage.js","js/data.js","data/generated/question-families.js","js/learning.js","js/question-interactions.js"];
self.addEventListener("install",e=>{e.waitUntil((async()=>{const c=await caches.open(CACHE_NAME);await Promise.allSettled(APP_SHELL.map(async a=>{const r=await fetch(new Request(a,{cache:"no-store"}));if(r.ok)await c.put(a,r);}));})());self.skipWaiting();});
self.addEventListener("activate",e=>{e.waitUntil((async()=>{const ks=await caches.keys();await Promise.all(ks.filter(k=>k.startsWith("studo-")&&k!==CACHE_NAME).map(k=>caches.delete(k)));await self.clients.claim();})());});
self.addEventListener("message",e=>{if(e.data==="SKIP_WAITING")self.skipWaiting();});
self.addEventListener("fetch",e=>{const r=e.request;if(r.method!=="GET")return;const u=new URL(r.url);if(u.origin!==self.location.origin)return;e.respondWith(networkFirst(r));});
function cacheable(r,u){if(u.pathname.toLowerCase().endsWith(".pdf"))return false;if(r.mode==="navigate")return true;if(["script","style","image","font","manifest"].includes(r.destination))return true;return u.pathname.toLowerCase().endsWith(".json");}
async function fallback(c,r){const exact=await c.match(r);if(exact)return exact;if(r.mode==="navigate"){const u=new URL(r.url);const byPath=await c.match(u.pathname.replace(/^\//,""));if(byPath)return byPath;return c.match("offline.html");}return null;}
async function networkFirst(r){const c=await caches.open(CACHE_NAME);const u=new URL(r.url);try{const res=await fetch(new Request(r,{cache:"no-store"}));if(res.ok&&cacheable(r,u))c.put(r,res.clone()).catch(()=>{});if(!res.ok&&res.status>=500){const f=await fallback(c,r);if(f)return f;}return res;}catch(err){const f=await fallback(c,r);if(f)return f;throw err;}}
