UNITS = [
{
'id':'understand-map-sources','slug':'understand-map-sources','title':'Understand & Map the Sources','skills':['W1.1','W1.2'],
'goal':'Understand exactly what the ER asks and build a fast map of both arguments before choosing a stronger source.',
'explain':'The Extended Response is not a personal-opinion essay. You read two arguments, identify what each source claims, what evidence it uses, how the reasoning works, and what limits the source admits or ignores. A source map gives you the raw material for a fair judgment.',
'contrast':'Summary tells what a source says. Mapping separates claim, evidence, reasoning, and limitation so you can evaluate the argument. Personal agreement is different again: you may disagree with the better-supported source and still choose it.',
'wording':'Prompts may ask which position is better supported, which source uses stronger evidence, or how the authors support their claims.',
'method':['Read the prompt and circle the task verb: analyze, evaluate, determine.','For Source A, note claim -> evidence -> reasoning -> limitation.','Repeat for Source B.','Do not choose a winner until both maps are complete.','Mark any place where a source predicts, assumes, or qualifies something.'],
'example_text':'Source A reports a six-month pilot with measured results and admits the sample was small. Source B raises two possible risks but gives no data showing they occurred.',
'example_q':'What should the map record?',
'example_reason':'A map should record Source A\'s measured evidence and limitation, and Source B\'s risks plus the missing support. That makes the later comparison evidence-based.',
'example_answer':'Map both sources first; judge second.',
' traps':[],
'common_traps':['Choosing the side you personally like.','Copying facts without identifying what claim they support.','Ignoring a limitation because it seems to weaken your preferred source.','Treating a prediction as if it were measured evidence.'],
'diagnostic':['If your notes are mostly full sentences, shorten them to claim/evidence/reasoning/limit labels.','If you choose a winner immediately, force yourself to write one strength and one weakness for each source first.','If your map has no limitations, check for words such as may, could, limited, only, or however.'],
'quick_text':'A source reports a 12 percent improvement in a pilot but notes that only two sites participated.',
'quick_q':'What are the evidence and limitation?',
'quick_answer':'Evidence: 12 percent improvement. Limitation: only two sites participated.',
'wb1':[('The prompt says: Determine which position is better supported by evidence.','Write the task in your own words.','Judge the two sources by their support; do not give only personal opinion.'),('Source A recommends expansion after a pilot; Source B recommends delay because costs may rise.','Write each main claim in one line.','A: expand after pilot. B: delay because of possible cost risk.'),('A source gives a survey percentage and then recommends a policy.','Label the percentage.','Evidence, if it is relevant to the policy claim.'),('A source says its pilot lasted only eight weeks.','Label this detail.','A limitation that narrows how confidently the result can be generalized.')],
'wb2':[('Source A has measured outcomes but a small sample. Source B has a broad survey but no before-and-after data.','Make a four-part map for each source.','Separate claim, evidence, reasoning, and limitation; do not decide the winner until both maps are complete.'),('A writer says, "The program could reduce costs" after one short example.','What should your map flag?','A qualified prediction plus limited evidence scope.'),('Both sources use statistics, but one statistic measures the claimed outcome while the other measures preference.','What should your map note?','The evidence types are different; do not treat all numbers as equally relevant.'),('A source admits another factor may have affected the result.','How should that appear in your map?','As a limitation or alternative explanation, not automatically as proof the source is weak.')]
},
{
'id':'choose-stronger-argument','slug':'choose-stronger-argument','title':'Choose the Stronger Argument','skills':['W1.3'],
'goal':'Choose the better-supported source by comparing relevance, sufficiency, reasoning, credibility, and limitations.',
'explain':'The stronger argument is not the louder or more confident one. It is the source whose evidence actually fits its claim, whose reasoning connects evidence to recommendation, and whose conclusion matches the limits of the evidence.',
'contrast':'A valid concern is not automatically a strong argument. A source can raise a real risk but still be weaker if it does not show the risk occurred or outweighs measured results.',
'wording':'Questions may ask which argument is better supported, which source is more convincing, or which evidence most strengthens or weakens a position.',
'method':['Test relevance: does the evidence measure the claimed issue?','Test sufficiency: is there enough support for the size of the conclusion?','Test reasoning: does the conclusion actually follow?','Test credibility and limitations: is the source fair about uncertainty?','Compare both sides using the same standards, then choose.'],
'example_text':'Source A gives pilot results, cost data, and a limited expansion plan. Source B predicts vandalism but gives no repair records.',
'example_q':'Which source is stronger?',
'example_reason':'Source A directly measures the program and matches its recommendation to the evidence. Source B raises a possible risk without showing that it happened.',
'example_answer':'Source A is better supported.',
'common_traps':['Counting the number of statistics instead of checking relevance.','Assuming a cautious tone means a cautious argument is stronger.','Rejecting a source because it admits a limitation.','Calling the weaker source completely wrong instead of identifying the support gap.'],
'diagnostic':['If both sources feel equal, compare the single strongest evidence item from each.','If you keep choosing the more confident writer, hide the recommendation and judge the evidence first.','If you write "has more facts," specify what those facts actually prove.'],
'quick_text':'Source A reports measured outcomes from the exact program being debated. Source B relies on two possible problems that were not measured.',
'quick_q':'Which has the stronger support and why?',
'quick_answer':'Source A, because its evidence directly tests the program outcomes.',
'wb1':[('A source gives before-and-after results for the policy being debated.','What strength does this create?','Direct relevance to the claimed outcome.'),('A source predicts a future cost increase but gives no budget estimate.','What weakness is present?','Unsupported prediction or insufficient evidence.'),('A source admits the pilot covered only two locations.','Does this automatically make it weak?','No. The limitation can make the reasoning more accurate if the recommendation stays limited.'),('Two sources disagree. One uses an actual pilot; the other uses one anecdote.','What should you compare?','Scope and relevance of evidence, not simply which source has numbers.')],
'wb2':[('Source A uses a 1,000-person survey about preference. Source B uses a 100-person trial measuring the actual outcome.','Which evidence may be more relevant?','Source B may be more relevant if the question is about the measured outcome, despite the smaller sample.'),('A source raises a valid concern and proposes further study.','How can it still be weaker?','If it lacks evidence showing the concern is large enough to outweigh the other source\'s measured support.'),('A source uses one city as evidence for a national conclusion.','What should you test?','Whether the conclusion is broader than the evidence supports.'),('A source reports mixed results and recommends a small pilot.','Why may this be strong reasoning?','The recommendation matches uncertainty instead of overstating the evidence.')]
},
{
'id':'thesis-evidence','slug':'thesis-evidence','title':'Thesis & Evidence','skills':['W1.4','W1.5'],
'goal':'Write a clear evaluative thesis and choose evidence that directly supports each reason in that thesis.',
'explain':'A useful ER thesis names the better-supported source and previews why. Evidence should then match those reasons exactly. If your reason is productivity, use productivity evidence; if your reason is credibility, use evidence about methods, limitations, or source fit.',
'contrast':'A thesis is not "Both sources discuss..." and it is not "I agree with...". Evidence is not any interesting fact; it is the fact that performs the job your paragraph claims it performs.',
'wording':'You may need to choose the best thesis, select the most relevant evidence, or revise a claim that overstates what a source proves.',
'method':['Name the stronger source.','Give one or two evidence-based reasons.','Keep the source\'s qualifiers and scope.','For each body reason, select one or two specific evidence items.','Reject evidence that is true but measures a different outcome.'],
'example_text':'A pilot reports 12 percent more completed projects and 78 percent schedule preference.',
'example_q':'Which evidence supports productivity?',
'example_reason':'The 12 percent project increase measures work output. The 78 percent figure measures preference, a different claim.',
'example_answer':'Use the project-completion statistic for productivity.',
'common_traps':['Writing a topic statement instead of an evaluative thesis.','Using proves, always, or everyone when the source is limited.','Using preference evidence to prove performance.','Adding outside evidence not supplied in the task.'],
'diagnostic':['If your thesis could fit any topic, make the reasons more specific.','If evidence feels impressive but does not match the paragraph claim, replace it.','If your sentence makes the source more certain than the original, restore words such as may, some, or suggests.'],
'quick_text':'A source reports that missed appointments fell during a text-reminder pilot but notes that scheduling also changed.',
'quick_q':'Write one precise thesis reason.',
'quick_answer':'The source has measured appointment data and acknowledges another possible cause, which makes its support more careful.',
'wb1':[('Source A is stronger because it uses a measured pilot and addresses a stated limitation.','Identify the thesis judgment and two reasons.','Judgment: A is stronger. Reasons: measured pilot; response to limitation.'),('Evidence: 78 percent preferred the schedule.','What claim does this best support?','Employee preference or acceptance, not productivity.'),('Evidence: completed projects rose 12 percent.','What claim does this best support?','Productivity or performance.'),('"Source A proves the policy always works."','Revise the overstatement.','Source A provides stronger support that the policy worked in the pilot, while broader results remain uncertain.')],
'wb2':[('Write a thesis for a source with strong data but a limited sample.','Keep the judgment and limitation together.','Example: Source A is better supported because it reports measured results and limits its recommendation to a cautious expansion.'),('A paragraph argues that Source B lacks cost support.','Choose the best evidence type.','A missing budget comparison or absent cost estimate from Source B.'),('A source includes a strong statistic that does not relate to your paragraph reason.','Use it or cut it?','Cut or move it. Relevance is more important than impressive numbers.'),('A source says a policy may reduce delays.','Paraphrase without source drift.','The source suggests the policy may reduce delays; do not change may to will or proves.')]
},
{
'id':'analyze-not-summarize','slug':'analyze-not-summarize','title':"Analyze, Don't Just Summarize",'skills':['W1.6','W1.7'],
'goal':'Explain why evidence matters and evaluate the reasoning that connects evidence to a source\'s conclusion.',
'explain':'Summary tells the reader what the source says. Analysis tells the reader why that evidence makes the argument stronger or weaker. Strong ER body paragraphs repeatedly answer: What does this evidence show? Why is it relevant? How does it compare with the other source?',
'contrast':'"Source A says sales rose 20 percent" is summary. "The 20 percent increase directly measures the outcome Source A claims the policy improves" is analysis.',
'wording':'Questions may ask which sentence best analyzes evidence, identifies an assumption, or compares the reasoning in two sources.',
'method':['State one evaluative point.','Give specific evidence.','Explain why the evidence supports or weakens the claim.','Identify any reasoning gap, assumption, or limitation.','Compare with the other source when the comparison sharpens the judgment.'],
'example_text':'Source B uses one cafe patio to recommend shade sails for an entire district.',
'example_q':'What is the reasoning issue?',
'example_reason':'The conclusion covers a much larger area than the evidence. The source assumes one location is representative.',
'example_answer':'The evidence scope is too narrow for the district-wide conclusion.',
'common_traps':['Restating a statistic and calling it analysis.','Using "This proves" without explaining the connection.','Attacking the author instead of the reasoning.','Ignoring a valid point in the weaker source.'],
'diagnostic':['After every evidence sentence, add "This matters because..." and make the reason specific.','If your paragraph contains many source details but few because/therefore/comparison sentences, you may be summarizing.','If you call a source weak, name the exact missing link: relevance, sufficiency, assumption, or unsupported prediction.'],
'quick_text':'Source A measures eight blocks; Source B gives one patio example for a district-wide recommendation.',
'quick_q':'Write one analysis sentence.',
'quick_answer':'Source A is more persuasive on scope because its evidence covers several locations, while Source B generalizes from one example.',
'wb1':[('"Source A reports a 5-degree difference."','Turn summary into analysis.','The measured difference directly supports the claim that the treatment affected temperature in the studied locations.'),('A source moves from one example to a citywide recommendation.','Name the reasoning weakness.','Overgeneralization or insufficient evidence scope.'),('A source admits another factor may affect results.','How can you analyze this?','The limitation makes the reasoning more cautious and prevents a false single-cause claim.'),('A weaker source raises a valid concern.','How should you treat it?','Acknowledge it, then explain why the source does not support it enough to outweigh stronger evidence.')],
'wb2':[('Evidence sentence: "The pilot reduced defects from 31 to 19 per 10,000 units."','Add analysis and comparison.','Explain that it measures the exact defect category, then contrast it with an unsupported prediction from the other source.'),('A source uses an expert quote from an unrelated field.','What should you analyze?','Credibility fit: expertise matters only when it is relevant to the claim.'),('A source recommends a full rollout after a short pilot.','What reasoning question should you ask?','Does the size of the conclusion exceed what the pilot can support?'),('A source has fewer statistics but better cause-and-effect reasoning.','What matters?','Quality and relevance of support, not quantity of numbers.')]
},
{
'id':'organize-develop-revise','slug':'organize-develop-revise','title':'Organize, Develop & Revise','skills':['W1.8','W1.9','W1.10','W1.11'],
'goal':'Turn good analysis into a clear response with purposeful paragraphs, developed reasoning, precise revision, and readable Standard English.',
'explain':'Organization makes your reasoning easy to follow. Development makes each reason complete. Revision removes vague, repetitive, or source-drifting language. Editing fixes sentence-level problems that interfere with clarity.',
'contrast':'A five-paragraph template is not the goal by itself. A shorter response with clear thesis, developed body reasoning, and controlled language can be stronger than a longer response full of repetition.',
'wording':'Practice may ask you to order paragraph parts, choose a stronger revision, improve a transition, or edit grammar and punctuation in an analytical sentence.',
'method':['Use a short introduction: issue -> stronger source -> main reasons.','Give each body paragraph one main reason.','Use Point -> Evidence -> Analysis -> Comparison.','Revise vague words such as good/bad/stronger when you can name the actual evidence problem.','Edit sentence boundaries, agreement, punctuation, and source qualifiers.'],
'example_text':'Source B is bad and does not make sense.',
'example_q':'How should this be revised?',
'example_reason':'The sentence is vague. A better revision names the missing comparison or unsupported prediction.',
'example_answer':'Source B raises a cost concern but provides no estimate showing that the cost outweighs the measured benefit.',
'common_traps':['Writing a long hook instead of the thesis.','Putting several unrelated reasons in one paragraph.','Repeating stronger/better without explaining why.','Editing for fancy vocabulary instead of clarity.'],
'diagnostic':['If a paragraph feels scattered, underline its one main point; move or cut sentences that do not serve it.','If your conclusion introduces new evidence, move that evidence into the body.','If grammar mistakes make your meaning hard to follow, prioritize sentence boundaries and agreement before minor style changes.'],
'quick_text':'Source A is stronger and better and more supported because its evidence is stronger.',
'quick_q':'Revise for precision.',
'quick_answer':'Source A is better supported because its pilot data measures the policy\'s actual outcome.',
'wb1':[('Put these in order: analysis, evidence, point, comparison.','Create the paragraph sequence.','Point -> Evidence -> Analysis -> Comparison.'),('"Both sources discuss the library."','Revise into an evaluative introduction sentence.','Both sources discuss Sunday library hours, but Source A is better supported because it uses pilot attendance and cost data.'),('"Source B is bad."','Make it precise.','Name the exact weakness, such as no cost estimate or unsupported prediction.'),('A sentence joins two independent clauses with only a comma.','What should revision check?','Sentence boundary: use a period, semicolon, or comma plus coordinating conjunction as appropriate.')],
'wb2':[('Outline two body paragraphs using one reason each.','Use evidence and analysis under each.','Each body paragraph should have a distinct reason, matching evidence, explanation, and comparison.'),('A paragraph repeats the same statistic three times.','Revise the development.','State the statistic once, then spend space explaining its significance and comparing the other source.'),('A conclusion introduces a new survey.','What should you do?','Move the survey into a body paragraph or cut it; conclusions should close the reasoning.'),('Your sentence changes "may reduce" to "will eliminate."','What kind of revision is needed?','Restore source precision; do not strengthen the author\'s claim.')]
},
{
'id':'full-extended-response','slug':'full-extended-response','title':'Full Extended Response','skills':['W1.12'],
'goal':'Complete a full paired-source response in a realistic workflow, then use the three-trait rubric to review what to improve.',
'explain':'Full ER practice combines everything: read, map, judge, plan, draft, revise, and self-review. Timed simulation gives you 45 minutes. Untimed mode removes the countdown but keeps the same source-based task and review standard.',
'contrast':'The self-review is not an official score. Chee Skool does not know a machine-verified essay score in V1. Your provisional 0/1/2 trait choices are reflection data and stay separate from objective quiz accuracy.',
'wording':'The full prompt asks you to analyze both sources and determine which position is better supported by evidence and reasoning.',
'method':['0-8 min: read and map both sources.','8-12 min: choose the stronger source and outline two reasons.','12-37 min: draft with evidence and analysis.','37-45 min: revise source accuracy, organization, and sentence clarity.','After submission: self-review all three traits and compare with the model only after your own attempt.'],
'example_text':'Planner: Winner A | Reason 1 measured outcome | Evidence 19% less waste | Reason 2 limitation handled | B weakness unsupported odor prediction.',
'example_q':'Why is this planner useful?',
'example_reason':'It stores the reasoning chain in shorthand so drafting can focus on sentences rather than re-deciding the argument.',
'example_answer':'A compact planner protects both time and source accuracy.',
'common_traps':['Starting to draft before choosing the stronger source.','Spending too long on the introduction.','Quoting evidence without analysis.','Treating the model response as something to copy before attempting the prompt.','Treating self-score as an official GED score.'],
'diagnostic':['If you run out of time, shorten planning notes and introduction before cutting analysis.','If your draft is mostly source summary, add why-this-matters sentences after evidence.','If your self-score feels uncertain, use the observable checklist rather than judging whether the essay "sounds smart."'],
'quick_text':'You have 45 minutes and two sources. Your first impulse is to write the introduction immediately.',
'quick_q':'What should you do instead?',
'quick_answer':'Map both sources and decide the better-supported argument before drafting.',
'wb1':[('Create a 5-line planner from a paired-source prompt.','Include winner, two reasons, two evidence notes, and one weakness in the other source.','The planner should preserve the reasoning without full sentences.'),('Write only a two-sentence introduction.','Keep it efficient.','Sentence 1 frames the issue; sentence 2 names the stronger source and main reasons.'),('Write one Point -> Evidence -> Analysis -> Comparison paragraph.','Do not write a full essay yet.','The paragraph should explain why the evidence matters and compare the weaker source.'),('Self-review a sample paragraph on Trait 1 only.','Use observable evidence.','Check judgment, source evidence, and analysis rather than grammar.')],
'wb2':[('Plan a 45-minute response with time blocks.','Protect revision time.','Use roughly 8 min reading, 4 min planning, 25 min drafting, 8 min revising.'),('Write an untimed full response, then highlight thesis/evidence/analysis/comparison.','Audit the reasoning.','Any large unhighlighted section may be summary, filler, or a missing function.'),('Give yourself provisional 0/1/2 trait scores.','Keep them separate from objective accuracy.','Each score should cite visible evidence in your own response.'),('Revise the same response once after model comparison.','Use the model diagnostically, not as a replacement.','Choose one reasoning improvement and one clarity/editing improvement to apply.')]
}
]
