import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
PASSAGES=ROOT/'content-src'/'passages'; SETS=ROOT/'content-src'/'sets'
PASSAGES.mkdir(parents=True,exist_ok=True); SETS.mkdir(parents=True,exist_ok=True)

def dump(p,o): p.write_text(json.dumps(o,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')

def passage(pid,title,text,context='workplace'):
    o={'schemaVersion':2,'id':pid,'title':title,'text':text.strip(),'textType':'informational','context':context,
       'source':{'type':'original','attribution':'Original content by Studo'},
       'rights':{'status':'original','holder':'Studo','note':'Original practice material created for Studo Language & Editing V1.'},
       'status':'published','version':1,'author':'Studo','reviewer':'Language & Editing V1 editorial review'}
    dump(PASSAGES/f'{pid}.json',o)

def q(qid,prompt,skill,family,choices,correct,why,tip,secondary=None,difficulty='medium',dok=2,qtype='grammar_edit',seconds=45):
    opts=[]
    for oid,text,wrong in choices:
        item={'id':oid,'text':text}
        if oid!=correct:
            item['distractorType']='editing_error'; item['whyWrong']=wrong
        opts.append(item)
    return {'id':qid,'type':qtype,'prompt':prompt,'primarySkillId':skill,
            **({'secondarySkillIds':secondary} if secondary else {}),'familyId':family,
            'difficulty':difficulty,'dok':dok,
            'difficultyProfile':{'textComplexity':1 if difficulty=='easy' else (2 if difficulty=='medium' else 3),
                                 'reasoningDepth':dok,'evidenceDistance':1 if difficulty=='easy' else 2,
                                 'distractorSimilarity':2 if difficulty!='hard' else 3,'sourceCount':1,'responseDemand':1},
            'points':1,'estimatedSeconds':seconds,'options':opts,'correct':correct,
            'explanation':{'answer':correct.upper(),'whyCorrect':why,'quickTip':tip}}

def focused(sid,title,desc,pid,unit,primary,secondary,questions):
    o={'schemaVersion':2,'id':sid,'runtime':{'id':sid,'file':f'{sid}.json'},'title':title,'description':desc,
       'subject':'rla','category':'language_conventions','topic':'Language & Editing - Focused Practice','difficulty':'medium',
       'status':'published','version':1,'passageRefs':[pid],'author':'Studo','reviewer':'Language & Editing V1 editorial review',
       'reviewNotes':'Reviewed for one-best-answer grammar logic, contextual editing, close distractors, and specific feedback.',
       'questions':questions,'curriculum':{'domain':'Language & Editing','primarySkillId':primary,'secondarySkillIds':secondary,
       'unitId':unit,'contentKind':'skill_drill','learningObjective':desc,'topicLabel':'Focused Practice'}}
    dump(SETS/f'{sid}.json',o)

def mixed(sid,title,desc,pid,primary,secondary,tags,questions):
    o={'schemaVersion':2,'id':sid,'runtime':{'id':sid,'file':f'{sid}.json'},'title':title,'description':desc,
       'subject':'rla','category':'language_conventions','topic':'Language & Editing - GED Practice','difficulty':'hard',
       'status':'published','version':1,'passageRefs':[pid],'author':'Studo','reviewer':'Language & Editing V1 editorial review',
       'reviewNotes':'Mixed editing passage reviewed for sentence-context fidelity, one-best-answer grammar logic, and GED-style editing transfer.',
       'questions':questions,'curriculum':{'domain':'Language & Editing','primarySkillId':primary,'secondarySkillIds':secondary,
       'contentKind':'editing_practice','practiceTags':tags,'learningObjective':'Edit grammar, punctuation, usage, and clarity in passage context.','topicLabel':'Mixed Editing Practice'}}
    dump(SETS/f'{sid}.json',o)

# ---------- Focused units ----------
passage('p-rla-lang-word-choice','Updating the Volunteer Handbook', '''
The Riverside Community Center is revising its volunteer handbook before a new group begins work next month. The old handbook was written quickly and contains several expressions that are common in casual speech but are not appropriate for a formal workplace guide. The coordinator wants the new version to sound clear and professional without becoming stiff or difficult to read.

One section explains where volunteers should leave personal items, how they should report schedule changes, and whom they should contact if they cannot attend a shift. Another section describes the effect of late arrivals on the front desk, where only two people may be available during busy periods. The coordinator also wants to distinguish between rules that apply to all volunteers and suggestions that simply make the work easier.

During editing, the team agrees to avoid unnecessary slang and to choose words according to their exact grammatical job. They also check commonly confused words instead of relying only on how a sentence sounds. The goal is not to make every sentence formal for its own sake. The goal is to use standard English that is precise, respectful, and easy for volunteers to follow.
''','community')
qs=[
q('q1','Volunteers should place {{blank}} bags in the lockers before beginning a shift.','L1.1','language.usage.confused_words',[('a','there',"'There' refers to a place, not ownership."),('b','their',''),('c',"they're","'They're' means 'they are' and cannot modify 'bags'."),('d','theirs',"'Theirs' stands alone and does not come directly before a noun.")],'b',"'Their' is the possessive determiner needed before 'bags'.","Check the grammatical job: ownership before a noun requires 'their'.",difficulty='easy',dok=1),
q('q2','The new sign may {{blank}} how quickly visitors find the correct desk.','L1.1','language.usage.confused_words',[('a','effect',"As a noun, 'effect' usually means a result; the sentence needs a verb meaning influence."),('b','affect',''),('c','effects',"This plural noun form cannot follow 'may'."),('d','affected',"A modal verb such as 'may' takes the base form, not the past tense.")],'b',"'Affect' is the verb meaning to influence something.","After may/can/will, use the base verb and check affect (verb) versus effect (usually noun)."),
q('q3','The revised handbook contains {{blank}} unclear instructions than the old version.','L1.1','language.usage.confused_words',[('a','less',"'Less' is generally used with uncountable amounts; 'instructions' are countable."),('b','fewer',''),('c','fewest',"The sentence compares two versions, so a comparative form is needed, not a superlative."),('d','little',"'Little' does not correctly modify the plural count noun 'instructions'.")],'b',"'Fewer' is used with countable plural nouns such as 'instructions'.","Ask whether you can count the noun: fewer instructions, less confusion."),
q('q4','Which revision uses standard English? “Volunteers could of called before missing the shift.”','L1.4','language.usage.standard_usage',[('a','Volunteers could of called before missing the shift.',"'Could of' is a nonstandard spelling based on the sound of 'could've'."),('b','Volunteers could have called before missing the shift.',''),('c','Volunteers could had called before missing the shift.',"'Could had' is not the standard modal construction."),('d','Volunteers could having called before missing the shift.',"A modal cannot be followed by the -ing form in this construction.")],'b',"'Could have called' is the standard modal-perfect construction.","When speech sounds like 'could of,' check whether the intended form is 'could have'."),
q('q5','The coordinator divided the tasks {{blank}} the three new volunteers.','L1.1','language.usage.confused_words',[('a','between',"'Between' is possible with more than two in some contexts, but here the sentence simply distributes tasks within a group; 'among' is the clearer standard choice."),('b','among',''),('c','beside',"'Beside' means next to and does not express distribution."),('d','through',"'Through' does not express distribution to members of a group.")],'b',"'Among' clearly expresses distribution within a group of three volunteers.","Choose the preposition that expresses the exact relationship, not just a familiar phrase."),
q('q6','Which sentence best fits a formal volunteer handbook?','L1.4','language.usage.standard_usage',[('a','If you gotta leave early, tell somebody up front.',"This uses casual forms such as 'gotta' and the vague word 'somebody'."),('b','If you need to leave early, notify the shift coordinator before you go.',''),('c','If you wanna bounce early, give the desk a heads-up.',"This uses slang that is inappropriate for a formal handbook."),('d','If early leaving happens, communication should maybe occur.',"This is vague and awkward rather than clear standard usage.")],'b',"The sentence is professional, specific, and natural without unnecessary formality.","Formal standard English should be clear and precise, not slangy or inflated.",qtype='multiple_choice'),
q('q7','The change had an immediate {{blank}} on front-desk coverage.','L1.1','language.usage.confused_words',[('a','affect',"The sentence needs a noun after 'an immediate'; 'affect' is normally the verb here."),('b','effect',''),('c','affects',"This is a verb form and does not fit after the article 'an'."),('d','effective',"This adjective would need to modify a noun rather than stand as the noun itself.")],'b',"'Effect' is the noun meaning a result or consequence.","Use affect for the action and effect for the result in most RLA editing contexts."),
q('q8','Choose the clearest standard revision: “Irregardless of experience, every volunteer reviews the safety rules.”','L1.4','language.usage.standard_usage',[('a','Regardless of experience, every volunteer reviews the safety rules.',''),('b','Irregardless of experience, every volunteer reviews the safety rules.',"'Irregardless' is widely used but is not the preferred standard form for formal editing."),('c','Without regards of experience, every volunteer reviews the safety rules.',"'Without regards of' is not the standard idiom for this meaning."),('d','Regardlessly of experience, every volunteer reviews the safety rules.',"'Regardlessly' is not the standard form needed here.")],'a',"'Regardless of' is the standard expression and preserves the intended meaning.","In editing questions, prefer the standard form that says the same thing clearly.")]
focused('set-rla-lang-word-choice','Handbook Word Choice','Choose standard, precise words in a formal workplace context.','p-rla-lang-word-choice','word-choice-standard-usage','L1.1',['L1.4'],qs)

passage('p-rla-lang-agreement','Preparing the Inventory Report', '''
At the end of each month, a small electronics shop prepares an inventory report. The report lists items that are running low, equipment that needs repair, and supplies that should be reordered. Because several employees contribute notes, the final draft often contains agreement and pronoun problems that are easy to miss during a quick read.

The store manager reminds the team that the grammatical subject controls the verb even when another noun appears closer to it. Phrases such as “along with the spare cables” or “of the replacement parts” can distract an editor from the true subject. Compound subjects and indefinite pronouns require attention as well because they do not always follow the pattern a reader expects from casual speech.

Pronouns create a different problem. A pronoun must clearly refer to the intended noun, and its form must fit its job in the sentence. If two possible nouns appear before “it” or “they,” the sentence may need to be rewritten rather than merely corrected for number. The team’s goal is simple: a reader should never have to stop and guess who completed an action, which item is being discussed, or whether the verb belongs with a nearby distractor instead of the actual subject.
''','workplace')
qs=[
q('q1','The box of replacement cables {{blank}} beside the service counter.','L1.2','language.grammar.subject_verb_agreement',[('a','are',"'Cables' is inside a prepositional phrase; it is not the subject."),('b','is',''),('c','have been',"This plural verb phrase does not agree with the singular subject 'box'."),('d','were',"This changes both number and tense without support from the sentence.")],'b',"The subject is the singular noun 'box,' so 'is' agrees with it.","Cross out interrupting prepositional phrases before matching subject and verb."),
q('q2','Neither of the two scanners {{blank}} working correctly today.','L1.7','language.grammar.complex_agreement',[('a','are',"'Neither' is singular in this construction even though 'scanners' is plural."),('b','is',''),('c','were',"This shifts the sentence to past tense and still misses the singular subject."),('d','have',"'Have' is plural and does not agree with 'neither'.")],'b',"'Neither' is the grammatical subject and takes the singular verb 'is'.","With neither/either, find the actual subject instead of matching the nearest plural noun."),
q('q3','Maya asked Jordan and {{blank}} to verify the count.','L1.3','language.pronoun.case',[('a','I',"After the verb 'asked,' the pronoun is an object, so the subject form 'I' is incorrect."),('b','me',''),('c','my',"'My' is possessive and must modify a noun."),('d','mine',"'Mine' is possessive and does not serve as the object of 'asked' here.")],'b',"'Me' is the object form required after 'asked'.","Remove the other name: 'Maya asked me' makes the correct case easier to hear."),
q('q4','Choose the clearest revision: “When Leo placed the tablet beside the charger, it was damaged.”','L1.3','language.pronoun.reference',[('a','When Leo placed the tablet beside the charger, it was damaged.',"'It' could refer to either the tablet or the charger."),('b','Leo placed the damaged tablet beside the charger.',''),('c','When Leo placed it beside it, the damage was visible.',"Replacing both nouns with pronouns makes the reference even less clear."),('d','The tablet and charger were beside it when Leo noticed damage.',"'It' still lacks a clear antecedent.")],'b',"Naming the damaged item removes the ambiguous pronoun reference.","If a pronoun could point to two nouns, rewrite with the exact noun rather than guessing."),
q('q5','The manager, together with two assistants, {{blank}} the final inventory.','L1.7','language.grammar.complex_agreement',[('a','review',"The phrase 'together with two assistants' does not make the singular subject plural."),('b','reviews',''),('c','have reviewed',"This plural verb does not agree with the singular subject 'manager'."),('d','were reviewing',"This plural past-progressive form changes both agreement and tense.")],'b',"The true subject is 'manager,' so the singular verb 'reviews' is correct.","Phrases beginning with together with, along with, or as well as do not change the subject."),
q('q6','Each technician should record {{blank}} own inspection notes before leaving.','L1.3','language.pronoun.agreement',[('a','their',''),('b','our',"'Our' changes the person and does not refer to 'each technician'."),('c','your',"'Your' addresses the reader instead of referring back to the third-person subject."),('d','its',"'Its' is normally used for things or organizations, not a person in this context.")],'a',"Singular 'they/their' is standard and clearly refers back to 'each technician'.","Make pronouns agree in person and reference; singular they is acceptable in standard English."),
q('q7','The invoices and the repair log {{blank}} stored in the locked cabinet.','L1.2','language.grammar.subject_verb_agreement',[('a','is',"Two nouns joined by 'and' form a plural subject here."),('b','are',''),('c','has been',"This singular verb phrase does not agree with the compound subject."),('d','was',"The singular past-tense verb does not match the plural subject.")],'b',"The compound subject 'invoices and repair log' is plural, so it takes 'are'.","Subjects joined by and are usually plural unless they name one combined thing."),
q('q8','Either the supervisors or the store manager {{blank}} the closing report tonight.','L1.7','language.grammar.complex_agreement',[('a','approve',"With either/or, the verb normally agrees with the nearer subject; 'manager' is singular."),('b','approves',''),('c','have approved',"This plural verb does not agree with the nearer singular subject."),('d','were approving',"This changes tense and uses plural agreement.")],'b',"With subjects joined by either/or, the verb agrees with the nearer subject, 'store manager'.","For either/or and neither/nor, check the subject closest to the verb.")]
focused('set-rla-lang-agreement','Inventory Agreement & Pronouns','Edit agreement and pronoun problems without being distracted by nearby nouns.','p-rla-lang-agreement','agreement-pronouns','L1.2',['L1.3','L1.7'],qs)

passage('p-rla-lang-modifiers','A Walkway Inspection Note', '''
A facilities assistant is revising a short report about a slippery walkway outside an office building. The first draft contains several sentences in which descriptive phrases are placed too far from the words they are meant to modify. In a safety report, that problem can create more than awkward style: it can make the reader misunderstand who observed a condition or what was actually damaged.

The assistant begins by checking introductory phrases. If a sentence starts with “After inspecting the walkway,” the noun immediately after the comma should be the person who performed the inspection. A walkway cannot inspect itself. The assistant also checks limiting words such as “only,” because moving them can change meaning. “Only staff used the west entrance” does not mean the same thing as “Staff used only the west entrance.”

Finally, the assistant reviews long noun phrases and descriptive clauses. Details should sit close enough to their targets that a reader does not attach them to the wrong noun. When several revisions are grammatically possible, the best one is the version that makes the intended relationship unmistakable without adding unnecessary words.
''','workplace')
qs=[
q('q1','Choose the best revision: “After inspecting the walkway, several loose tiles were reported by Mina.”','L1.5','language.modifiers.placement',[('a','After inspecting the walkway, several loose tiles were reported by Mina.',"The opening phrase illogically suggests that the tiles performed the inspection."),('b','After inspecting the walkway, Mina reported several loose tiles.',''),('c','Several loose tiles, after inspecting the walkway, were reported by Mina.',"This still makes the tiles appear to perform the inspection."),('d','Mina reported, after inspecting, the walkway several loose tiles.',"The word order is awkward and obscures what was inspected.")],'b',"Mina is placed directly after the introductory phrase, so the sentence clearly identifies who inspected the walkway.","After an introductory modifier, name the person or thing that actually performs the action."),
q('q2','Which sentence means that staff used the west entrance and no other entrance?','L1.5','language.modifiers.limiting_words',[('a','Only staff used the west entrance.',"This means no one except staff used that entrance; it does not limit which entrance staff used."),('b','Staff only used the west entrance.',"In careful editing, placing 'only' before the verb can ambiguously limit the action rather than the object."),('c','Staff used only the west entrance.',''),('d','Staff used the west only entrance.',"This incorrectly suggests the west entrance is the only entrance that exists.")],'c',"Placing 'only' directly before 'the west entrance' limits the object and gives the intended meaning.","Put limiting words such as only as close as possible to the word or phrase they limit."),
q('q3','Choose the clearest revision: “The crew replaced the railing near the stairs that was rusted.”','L1.5','language.modifiers.placement',[('a','The crew replaced the railing that was rusted near the stairs.',''),('b','Near the stairs that was rusted, the crew replaced the railing.',"This makes the stairs appear to be rusted and also creates an agreement problem."),('c','The crew near the stairs replaced the railing that was rusted.',"This shifts 'near the stairs' to describe the crew rather than the railing location."),('d','The rusted crew replaced the railing near the stairs.',"This absurdly makes 'rusted' describe the crew.")],'a',"The relative clause 'that was rusted' sits directly after 'railing,' the noun it describes.","Keep descriptive clauses beside the noun they modify."),
q('q4','Which revision fixes the dangling modifier? “While walking to the entrance, the broken light was easy to notice.”','L1.5','language.modifiers.dangling',[('a','While walking to the entrance, the broken light was easy to notice.',"The sentence suggests the broken light was walking."),('b','While walking to the entrance, I easily noticed the broken light.',''),('c','The broken light was walking to the entrance and easy to notice.',"This changes the meaning and creates an illogical subject."),('d','Walking to the entrance was the broken light that I noticed.',"The sentence remains illogical and awkward.")],'b',"The subject 'I' is the person who was walking, so the opening phrase now has a logical target.","Ask who is doing the action in the opening phrase; name that subject immediately after the comma."),
q('q5','Choose the clearest sentence.','L1.5','language.modifiers.placement',[('a','The supervisor nearly reviewed every report before noon.',"This can mean the supervisor almost reviewed them but did not actually do so."),('b','The supervisor reviewed nearly every report before noon.',''),('c','Nearly the supervisor reviewed every report before noon.',"'Nearly' is placed where it cannot logically modify the intended quantity."),('d','The supervisor reviewed every nearly report before noon.',"The modifier is in an ungrammatical position.")],'b',"'Nearly' directly modifies 'every report,' showing that most but not all reports were reviewed.","Place degree and limiting modifiers beside the quantity or action they actually limit."),
q('q6','Which revision makes the intended meaning clearest? “We saw a damaged sign beside the loading dock with a flashlight.”','L1.5','language.modifiers.placement',[('a','With a flashlight, we saw a damaged sign beside the loading dock.',''),('b','We saw with a damaged sign a loading dock beside the flashlight.',"The revision destroys the intended relationships among the details."),('c','We saw a damaged sign with a flashlight beside the loading dock.',"This can make it sound as though the sign had the flashlight."),('d','Beside the flashlight, the loading dock saw a damaged sign.',"The loading dock cannot perform the action of seeing.")],'a',"Moving 'with a flashlight' to the beginning clearly shows how 'we' saw the sign.","When a phrase could attach to two nouns, move it next to the word or action it truly describes."),
q('q7','Choose the best revision: “Covered in rainwater, the custodian placed a warning cone beside the puddle.”','L1.5','language.modifiers.placement',[('a','Covered in rainwater, the custodian placed a warning cone beside the puddle.',"This says the custodian was covered in rainwater, which is not the intended meaning."),('b','The custodian placed a warning cone beside the puddle that covered part of the walkway.',''),('c','The puddle placed a warning cone beside the custodian.',"This reverses the logical actor and action."),('d','A warning cone, covered in rainwater, placed the custodian beside the puddle.',"The cone cannot place the custodian.")],'b',"The descriptive clause now clearly explains that the puddle covered part of the walkway.","Check that every descriptive phrase has a logical noun to modify."),
q('q8','Which sentence avoids a misplaced modifier?','L1.5','language.modifiers.placement',[('a','The team found a cracked tile during the inspection near the doorway.',"'Near the doorway' could attach to the inspection rather than clearly to the tile."),('b','During the inspection, the team found a cracked tile near the doorway.',''),('c','The cracked team found a tile near the doorway during the inspection.',"'Cracked' incorrectly modifies 'team'."),('d','Near the doorway found the team a cracked tile.',"The word order is not standard English.")],'b',"The time phrase is separated from the location phrase, making each modifier's job clear.","Place time, location, and descriptive phrases where their targets are unmistakable.")]
focused('set-rla-lang-modifiers','Walkway Modifier Check','Place modifiers so every description attaches to the intended word or action.','p-rla-lang-modifiers','modifiers-sentence-logic','L1.5',[],qs)

passage('p-rla-lang-parallel','Planning the Training Session', '''
A department is preparing a short orientation for new employees. The draft agenda includes three goals: introducing the safety process, explaining how to request equipment, and showing employees where to report problems. Because the agenda will be read aloud and posted online, the editor wants its sentence patterns to be easy to follow.

Parallel structure helps readers recognize items that have the same role. If a sentence begins “The session will explain how to sign in, how to request a key, and how to report a hazard,” each item follows the same pattern. Mixing “to sign in,” “requesting a key,” and “how hazards are reported” makes the list harder to process even if the general meaning remains understandable.

The editor also checks how complete ideas are connected. Two independent clauses may be joined with a coordinating conjunction or separated with appropriate punctuation. A dependent idea should be attached to a complete clause rather than left as a fragment. The goal is not to make every sentence the same length. It is to show the relationship among ideas through balanced structure and deliberate connections.
''','workplace')
qs=[
q('q1','Choose the parallel revision: “The session covers signing in, how to request keys, and reporting hazards.”','L1.6','language.parallelism.structure',[('a','The session covers signing in, requesting keys, and reporting hazards.',''),('b','The session covers to sign in, requesting keys, and hazards are reported.',"The three items use different grammatical patterns."),('c','The session covers signing in, how to request keys, and hazards.',"The final item is a noun while the others describe actions."),('d','The session covers sign in, requests for keys, and reporting hazards.',"The list mixes a bare verb, noun phrase, and gerund.")],'a',"All three items use matching -ing forms: signing, requesting, reporting.","Items with the same role should use the same grammatical form."),
q('q2','Complete the correlative structure: “The trainer will not only review the rules but also {{blank}}.”','L1.6','language.parallelism.correlative',[('a','demonstrating the equipment',"'Review' is a base verb; the paired item should match that form."),('b','demonstrate the equipment',''),('c','a demonstration of the equipment',"This noun phrase is not parallel with the verb 'review'."),('d','the equipment will be demonstrated',"This passive clause breaks the parallel structure.")],'b',"'Review' and 'demonstrate' are parallel base verbs after 'will'.","With not only/but also, compare the grammatical form immediately after each half."),
q('q3','Choose the best connection: “The room was full, {{blank}} the trainer opened the second training area.”','L1.6','language.connections.coordination_subordination',[('a','because',"'Because' would make the first clause depend on a reason that has not been stated in the intended order."),('b','so',''),('c','although',"'Although' signals contrast, but the second action is a result of the first condition."),('d','for example',"The second clause is a result, not an example of the room being full.")],'b',"'So' correctly shows that opening the second area was a result of the first room being full.","Choose a connector that names the actual relationship: addition, contrast, cause, or result."),
q('q4','Which sentence correctly subordinates the reason?','L1.6','language.connections.coordination_subordination',[('a','Because the projector failed. The trainer used printed diagrams.',"The dependent clause is incorrectly left as a fragment."),('b','Because the projector failed, the trainer used printed diagrams.',''),('c','The projector failed, because. The trainer used printed diagrams.',"'Because' is stranded and the punctuation is incorrect."),('d','Because the projector failed; the trainer used printed diagrams.',"A semicolon cannot directly separate a dependent clause from the main clause it depends on.")],'b',"The dependent reason clause is correctly attached to the independent clause with a comma.","A clause beginning with because usually needs a complete main clause attached to it."),
q('q5','Choose the parallel sentence.','L1.6','language.parallelism.structure',[('a','Employees should arrive on time, bring identification, and to wear closed shoes.',"The final item uses 'to wear' while the first two use base verbs."),('b','Employees should arrive on time, bring identification, and wear closed shoes.',''),('c','Employees should arriving on time, bring identification, and closed shoes.',"The list mixes a participle, verb, and noun phrase."),('d','Employees should arrive on time, identification is brought, and wear closed shoes.',"The middle item changes to a passive clause.")],'b',"All three actions use base verbs after the shared modal 'should'.","When a helping verb applies to a list, keep each listed verb in the same form."),
q('q6','Which revision best connects a contrast? “The training is brief. It covers the highest-risk tasks.”','L1.6','language.connections.coordination_subordination',[('a','Although the training is brief, it covers the highest-risk tasks.',''),('b','Because the training is brief, it covers the highest-risk tasks.',"'Because' incorrectly presents brevity as the cause of the coverage."),('c','The training is brief, so it covers the highest-risk tasks.',"'So' creates a cause-result relationship that the ideas do not support."),('d','The training is brief, for example it covers the highest-risk tasks.',"The second clause is not an example of brevity.")],'a',"'Although' correctly marks the contrast between short duration and broad importance.","Match the connector to the logic, not merely to what sounds smooth."),
q('q7','Choose the best revision: “The checklist is useful because it is short, clear, and employees can use it quickly.”','L1.6','language.parallelism.structure',[('a','The checklist is useful because it is short, clear, and quick to use.',''),('b','The checklist is useful because it is short, clarity, and employees use it quickly.',"The list mixes adjectives, a noun, and a clause."),('c','The checklist is useful because short, clear, and employees can use it quickly.',"The first two items are incomplete after 'because'."),('d','The checklist is useful because it is short, clearly, and quick use.',"The list mixes adjective, adverb, and noun forms.")],'a',"'Short,' 'clear,' and 'quick to use' function as parallel descriptions of the checklist.","Parallel ideas do not need identical word counts, but they should have matching grammatical roles."),
q('q8','Which sentence correctly joins two independent clauses?','L1.6','language.connections.coordination_subordination',[('a','The session ended early, the trainer stayed to answer questions.',"A comma alone cannot join two independent clauses; this is a comma splice."),('b','The session ended early, but the trainer stayed to answer questions.',''),('c','The session ended early because, the trainer stayed to answer questions.',"The connector and comma are incorrectly placed."),('d','The session ended early although. The trainer stayed to answer questions.',"'Although' is left incomplete and creates a fragment.")],'b',"A comma plus the coordinating conjunction 'but' correctly joins the two complete clauses and shows contrast.","For two complete clauses, use a period, semicolon, or comma plus a coordinating conjunction.")]
focused('set-rla-lang-parallel','Training Sentence Connections','Build parallel structures and connect clauses according to their logical relationship.','p-rla-lang-parallel','parallelism-sentence-connections','L1.6',[],qs)

passage('p-rla-lang-concision','Revising the Shuttle Notice', '''
A college transportation office is rewriting a notice about changes to its evening shuttle. The first draft was assembled from several emails, so it repeats information and uses transitions that do not always match the relationship between sentences. The editor wants students to understand the change quickly because many will read the notice on a phone while walking between buildings.

The revised notice should state the new departure time once, explain why the schedule changed, and tell riders where to find live updates. Repeating “at this point in time,” “due to the fact that,” and similar phrases makes the message longer without making it clearer. The editor replaces these expressions with shorter wording when no meaning is lost.

Transitions require a different kind of decision. “However” should introduce a contrast, while “therefore” should introduce a result. “For example” should lead into an illustration of the previous idea. A transition that sounds formal but names the wrong relationship can mislead a reader even if the grammar around it is correct. The final version should be concise, but it should never remove a condition, exception, or logical connection that riders need in order to act correctly.
''','school')
qs=[
q('q1','Choose the most concise revision: “At this point in time, the shuttle currently leaves at 8:30 p.m.”','L1.8','language.style.concision',[('a','At this point in time, the shuttle currently leaves at 8:30 p.m.',"'At this point in time' and 'currently' repeat the same idea."),('b','The shuttle currently leaves at 8:30 p.m.',''),('c','The shuttle, at this current point in time, leaves at 8:30 p.m.',"This preserves the redundant wording and adds interruption."),('d','Currently at this time now, the shuttle leaves at 8:30 p.m.',"'Currently,' 'at this time,' and 'now' repeat one another.")],'b',"The revision keeps the needed timing information and removes repeated phrases.","Cut words that duplicate meaning, not words that carry a condition or fact."),
q('q2','The 8:00 shuttle was often overcrowded; {{blank}}, the office added an 8:15 departure.','L1.9','language.transitions.logic',[('a','however',"'However' signals contrast, but the new departure is a response to the overcrowding."),('b','therefore',''),('c','for example',"The added departure is a result, not an example of overcrowding."),('d','meanwhile',"'Meanwhile' signals simultaneous timing rather than cause and result.")],'b',"'Therefore' correctly shows that the added departure resulted from overcrowding.","Name the relationship before choosing the transition."),
q('q3','Choose the clearest concise revision: “Students who are in possession of bicycles should use the exterior rack.”','L1.8','language.style.concision',[('a','Students with bicycles should use the exterior rack.',''),('b','Students who are in possession of bicycles should use the exterior rack.',"'Who are in possession of' is unnecessarily wordy."),('c','Bicycle-possessing students, in terms of the exterior rack, should utilize it.',"The sentence replaces simple wording with inflated and unclear language."),('d','Students, being those having bikes, should make usage of the exterior rack.',"This is wordier and less natural than the original.")],'a',"'Students with bicycles' states the same condition more directly.","Prefer the shortest wording that preserves the exact meaning."),
q('q4','The shuttle still serves the science building. {{blank}}, the library stop has moved one block east.','L1.9','language.transitions.logic',[('a','For example',"The library move is not an example of continuing science-building service."),('b','However',''),('c','Therefore',"The library stop did not move because the science-building service continues."),('d','Similarly',"The two facts are not similar; the second contrasts with the first by describing a change.")],'b',"'However' correctly signals that one part of the route remains the same while another has changed.","Use contrast transitions when the second statement limits or differs from the first."),
q('q5','Choose the best revision: “The reason the route changed is because road work blocks the usual turn.”','L1.8','language.style.concision',[('a','The route changed because road work blocks the usual turn.',''),('b','The reason the route changed is because road work blocks the usual turn.',"'The reason ... is because' redundantly expresses cause twice."),('c','The causal reason why the route changed is due to road work that blocks the usual turn.',"'Causal reason,' 'why,' and 'due to' make the sentence unnecessarily heavy."),('d','Road work is the reason because of which the route changed due to the blocked turn.',"This is wordy and awkward.")],'a',"The revision directly states the cause without repeating the cause relationship.","When because already gives the reason, you usually do not need 'the reason is because'."),
q('q6','Riders can view live bus locations in the app. {{blank}}, they can sign up for delay alerts.','L1.9','language.transitions.logic',[('a','In addition',''),('b','Nevertheless',"'Nevertheless' signals unexpected contrast, but the second sentence adds another service."),('c','As a result',"Signing up for alerts is not presented as a result of viewing locations."),('d','Instead',"The two options are both available; one does not replace the other.")],'a',"'In addition' correctly introduces another available service.","For another point with the same direction, use an addition transition rather than a cause or contrast word."),
q('q7','Choose the most concise sentence.','L1.8','language.style.concision',[('a','The office made a decision to extend service by thirty minutes. ',"'Made a decision to' can be replaced by the direct verb 'decided to'."),('b','The office decided to extend service by thirty minutes.',''),('c','The office came to a decision in regard to extending service by thirty minutes.',"This adds several unnecessary phrases."),('d','A decision was made by the office for the purpose of extending service by thirty minutes.',"The passive and purpose phrase make the sentence longer without adding meaning.")],'b',"The direct verb 'decided' expresses the same idea more efficiently.","Look for noun-heavy phrases that can become a direct verb."),
q('q8','The route change begins Monday. {{blank}}, riders should check the updated map before their first trip.','L1.9','language.transitions.logic',[('a','Consequently',''),('b','For instance',"Checking the map is a recommended result of the change, not an example of Monday."),('c','In contrast',"The advice does not contrast with the route change."),('d','Likewise',"The second statement is not a parallel example of the first.")],'a',"'Consequently' correctly introduces an action riders should take because the route is changing.","Result transitions should follow a fact that creates the need for the next action.")]
focused('set-rla-lang-concision','Shuttle Notice Editing','Make sentences concise and choose transitions that match the exact logic.','p-rla-lang-concision','concision-transitions','L1.8',['L1.9'],qs)

passage('p-rla-lang-boundaries','Community Center Renovation Memo', '''
A neighborhood community center will close one meeting room for renovation next week. Staff members are editing a memo that explains the temporary room changes, the construction schedule, and the location of evening programs. Because the memo contains several dates and conditions, sentence boundaries must be especially clear.

The first draft includes a few fragments created when dependent clauses were separated from the sentences they belong to. It also contains run-ons in which two complete ideas were joined only with a comma. The editor checks each sentence for a subject and a complete verb, then decides whether related complete clauses should be separated with a period, joined with a semicolon, or connected with a comma and an appropriate coordinating conjunction.

Punctuation inside sentences also matters. Nonessential information may need commas so readers can see the core sentence. A colon can introduce a list after a complete clause, but it should not be inserted directly after a verb when the sentence flows naturally into the list. The memo should feel simple, yet the punctuation must show exactly where one thought ends and the next begins.
''','community')
qs=[
q('q1','Choose the complete sentence.','L2.2','language.boundaries.fragments_runons',[('a','Because the east room will be closed for painting.',"This is a dependent clause and cannot stand alone."),('b','The east room will be closed for painting next Tuesday.',''),('c','While crews replace the ceiling panels.',"The clause begins with 'while' and lacks a main clause."),('d','After the evening programs move upstairs.',"This is an introductory dependent phrase, not a complete sentence.")],'b',"The sentence has a subject, a complete verb, and a complete thought.","If a sentence starts with because/while/after, check whether a main clause completes it."),
q('q2','Choose the correct revision: “The room closes Tuesday, evening classes move upstairs.”','L2.2','language.boundaries.fragments_runons',[('a','The room closes Tuesday; evening classes move upstairs.',''),('b','The room closes Tuesday, evening classes move upstairs.',"A comma alone cannot join these two independent clauses."),('c','The room closes Tuesday because. Evening classes move upstairs.',"'Because' is incomplete and creates a fragment."),('d','The room closes Tuesday evening classes move upstairs.',"Without punctuation or a connector, the sentence is fused.")],'a',"A semicolon correctly joins two closely related independent clauses.","Two complete clauses need a period, semicolon, or comma plus a coordinating conjunction."),
q('q3','Choose the correct punctuation: “The west room, which normally hosts art classes, {{blank}} remain open.”','L2.4','language.punctuation.clauses',[('a','will',''),('b',', will',"The opening comma already begins the nonessential clause; an extra comma before the verb would incorrectly separate subject and verb."),('c','; will',"A semicolon cannot separate the subject from its verb."),('d',': will',"A colon cannot separate the subject from its verb.")],'a',"The nonessential clause is already enclosed by commas, and no punctuation belongs between the subject and 'will remain'.","Remove the nonessential clause mentally; the core sentence should still read smoothly."),
q('q4','Choose the correct revision: “Staff will post signs at three locations the lobby, elevator, and west entrance.”','L2.4','language.punctuation.colon',[('a','Staff will post signs at three locations: the lobby, elevator, and west entrance.',''),('b','Staff will post signs at: three locations the lobby, elevator, and west entrance.',"A colon should not interrupt the phrase 'at three locations'."),('c','Staff will post signs: at three locations, the lobby, elevator, and west entrance.',"The wording before the colon does not introduce the list cleanly."),('d','Staff will post signs at three locations; the lobby, elevator, and west entrance.',"A semicolon should not introduce a simple list fragment.")],'a',"The complete clause ends with 'locations,' and the colon correctly introduces the list.","Use a colon after a complete clause that announces what follows."),
q('q5','Which revision fixes the comma splice? “The renovation starts Monday, it should finish by Friday.”','L2.2','language.boundaries.fragments_runons',[('a','The renovation starts Monday, and it should finish by Friday.',''),('b','The renovation starts Monday, it should finish by Friday.',"The comma splice remains unchanged."),('c','The renovation starts Monday because, it should finish by Friday.',"The connector is incomplete and the comma is misplaced."),('d','The renovation starts Monday it should finish by Friday.',"Removing the comma creates a fused sentence.")],'a',"A comma plus 'and' correctly joins the two independent clauses.","If both sides can stand alone, a comma needs a coordinating conjunction to join them."),
q('q6','Choose the correctly punctuated sentence.','L2.4','language.punctuation.clauses',[('a','The contractor said, that the hallway would stay open.',"A comma should not separate 'said' from the essential that-clause."),('b','The contractor said that the hallway would stay open.',''),('c','The contractor said; that the hallway would stay open.',"A semicolon cannot introduce a dependent that-clause."),('d','The contractor said: that the hallway would stay open.',"A colon is unnecessary before the that-clause.")],'b',"The essential that-clause follows 'said' without punctuation.","Do not insert punctuation just because a sentence feels long; identify the clause relationship first."),
q('q7','Choose the best revision: “Although the gym remains open. Some programs will move outside.”','L2.2','language.boundaries.fragments_runons',[('a','Although the gym remains open, some programs will move outside.',''),('b','Although the gym remains open. Some programs will move outside.',"The dependent clause beginning with 'although' is left as a fragment."),('c','Although. The gym remains open, some programs will move outside.',"'Although' is stranded and the relationship is broken."),('d','The gym remains open, although. Some programs will move outside.',"The connector is incomplete and creates another fragment.")],'a',"The dependent contrast clause is correctly attached to the main clause.","Attach an although-clause to the complete idea it modifies."),
q('q8','Which punctuation best completes the sentence? “One room will remain available {{blank}} the small conference room on the first floor.”','L2.4','language.punctuation.colon',[('a',':',''),('b',';',"The words after the blank are not an independent clause, so a semicolon is incorrect."),('c',',',"A comma does not clearly introduce the identifying example after the complete clause."),('d','.',"A period would leave 'the small conference room...' as a fragment.")],'a',"The complete clause introduces the one available room, so a colon cleanly presents the identifying phrase.","A colon can introduce an explanation or example after a complete clause.")]
focused('set-rla-lang-boundaries','Renovation Sentence Repair','Repair fragments, run-ons, and punctuation problems in a practical memo.','p-rla-lang-boundaries','sentence-boundaries-punctuation','L2.2',['L2.4'],qs)

passage('p-rla-lang-capitals','Museum Event Announcement', '''
A local history museum is preparing an announcement for a weekend program. The draft includes the names of staff members, departments, months, exhibits, and community partners, so the editor must decide which words require capitalization. The announcement also describes spaces and materials that belong to people or groups, which creates several opportunities for apostrophe errors.

The editor remembers that not every important-sounding noun is a proper noun. A job title is usually lowercase when it appears alone, but it may be capitalized when it comes directly before a person’s name as part of the name. Days, months, organizations, and official event names are capitalized. Generic descriptions usually are not.

For possession, the editor separates plural formation from ownership. Most singular nouns form the possessive with apostrophe + s. Regular plural nouns ending in s usually add only an apostrophe. Possessive pronouns such as its, theirs, and yours do not use apostrophes. The announcement should look polished, but every capital letter and apostrophe should have a grammatical reason rather than being added for emphasis.
''','community')
qs=[
q('q1','Choose the correct capitalization.','L2.1','language.capitalization.mechanics',[('a','The program begins on saturday, September 12.',"Days of the week are proper nouns and must be capitalized."),('b','The program begins on Saturday, September 12.',''),('c','The program begins on Saturday, september 12.',"Months are proper nouns and must be capitalized."),('d','The Program begins on Saturday, September 12.',"The common noun 'program' does not need capitalization here.")],'b',"Days and months are capitalized; the common noun 'program' is not.","Capitalize proper names and calendar names, not ordinary nouns for emphasis."),
q('q2','Choose the correct possessive form: “The {{blank}} office is beside the main gallery.”','L2.3','language.possessives.apostrophes',[('a',"curator's",''),('b','curators',"Without an apostrophe, 'curators' is simply plural and does not show that the office belongs to one curator."),('c',"curators'", "This form shows possession by multiple curators, but the sentence refers to one curator."),('d','curatorss',"This is not a standard plural or possessive form.")],'a',"A singular noun normally forms the possessive with apostrophe + s: curator's office.","First decide singular or plural; then add the possessive ending."),
q('q3','Choose the correct capitalization for a title used with a name.','L2.1','language.capitalization.mechanics',[('a','Museum director Elena Cruz will introduce the exhibit.',"When a formal title immediately precedes a name as part of the name, it is normally capitalized."),('b','Museum Director Elena Cruz will introduce the exhibit.',''),('c','museum Director Elena Cruz will introduce the exhibit.',"The capitalization is inconsistent and 'museum' is part of the title phrase here."),('d','Museum Director elena cruz will introduce the exhibit.',"Personal names must be capitalized.")],'b',"The formal title directly precedes Elena Cruz's name, so it is capitalized.","Capitalize a formal title before a name; lowercase it when used generically or after the name."),
q('q4','Choose the correct form: “The museum updated {{blank}} website before the event.”','L2.3','language.possessives.apostrophes',[('a',"it's", "'It's' means 'it is' or 'it has,' which does not fit before 'website'."),('b','its',''),('c',"its'", "The possessive pronoun 'its' never takes an apostrophe."),('d','it is',"'It is website' is not grammatically correct.")],'b',"'Its' is the possessive form; possessive pronouns do not use apostrophes.","Test 'it's' by expanding it to 'it is.' If that does not fit, use 'its'."),
q('q5','Choose the correct plural possessive: “The two {{blank}} schedules are posted online.”','L2.3','language.possessives.apostrophes',[('a',"guides'",''),('b',"guide's", "This shows possession by one guide, not two guides."),('c','guides',"This is plural but does not show possession of the schedules."),('d',"guides's", "A regular plural ending in s takes only an apostrophe for possession.")],'a',"'Guides' is a regular plural ending in s, so the possessive form is guides'.","For a regular plural already ending in s, add only the apostrophe."),
q('q6','Which sentence uses capitalization correctly?','L2.1','language.capitalization.mechanics',[('a','The museum will open its new river trade exhibit in October.',''),('b','The Museum will open its new River Trade Exhibit in October.',"Generic nouns and an unofficial descriptive exhibit name should not be capitalized without evidence they are formal names."),('c','The museum will open its new river trade exhibit in october.',"The month 'October' must be capitalized."),('d','The museum Will open its new river trade exhibit in October.',"A verb in the middle of a sentence is not capitalized without a special reason.")],'a',"Only the month is a proper name in this sentence; the other words are generic descriptions.","Do not capitalize common nouns just because they name an important place or event."),
q('q7','Choose the correct possessive phrase.','L2.3','language.possessives.apostrophes',[('a',"the childrens' activity room", "'Children' is an irregular plural that does not end in s, so possession requires apostrophe + s."),('b',"the children's activity room",''),('c','the childrens activity room',"The irregular plural is 'children,' and possession also needs an apostrophe."),('d',"the children's' activity room", "This adds an extra apostrophe after an already complete possessive form.")],'b',"The irregular plural 'children' forms the possessive as children's.","Irregular plurals not ending in s usually add apostrophe + s."),
q('q8','Choose the correct capitalization when the title follows the name.','L2.1','language.capitalization.mechanics',[('a','Elena Cruz, Museum Director, will speak at noon.',"A title used descriptively after a name is usually lowercase."),('b','Elena Cruz, museum director, will speak at noon.',''),('c','elena cruz, museum director, will speak at noon.',"Personal names must be capitalized."),('d','Elena Cruz, museum Director, will speak at noon.',"The common title is inconsistently capitalized.")],'b',"The job title follows the name and is used descriptively, so it is lowercase.","Formal titles are usually lowercase when they follow a person's name.")]
focused('set-rla-lang-capitals','Museum Mechanics Check','Edit capitalization and possessive forms according to their grammatical role.','p-rla-lang-capitals','capitalization-possessives','L2.1',['L2.3'],qs)

# ---------- Mixed editing passages ----------
mixed_specs=[]

def add_mixed(pid,sid,title,text,context,questions,tags,primary,secondary):
    passage(pid,title,text,context)
    mixed(sid,title,'Edit a full informational passage for grammar, punctuation, usage, and clarity.',pid,primary,secondary,tags,questions)

add_mixed('p-rla-lang-mixed-clinic','set-rla-lang-mixed-clinic','Updating the Clinic Reminder System','''
Harborview Clinic plans to revise the reminder messages it sends before appointments. Staff members began reviewing the system after noticing that missed appointments were especially common on Monday mornings. The clinic currently sends one text message at 6 p.m. the evening before each visit. Patients who do not use text messaging receive an automated phone call at the same time.

A three-week pilot tested an additional reminder on Friday afternoon for patients with Monday appointments. During the pilot, the number of missed Monday visits fell from an average of twenty-two per week to fifteen. Clinic managers caution that the pilot was short and that several other changes occurred at the same time. For example, reception staff also began confirming transportation needs for some older patients.

The clinic will continue the pilot for eight more weeks before deciding whether to use the extra reminder permanently. The scheduling team will track missed visits, canceled appointments, and the number of patients who ask to stop receiving messages. Staff members will also record whether patients report that the reminders are useful or excessive.

The revised public notice must explain the pilot without suggesting that the extra message has already been proven to solve the problem. It should also tell patients how to update their contact information and how to choose between text and phone reminders. Because the notice may be read quickly, the editor wants short sentences, clear transitions, and pronouns that refer to only one possible noun. The final version should sound professional while still being easy for patients to understand.
''','workplace',[
q('q1','Choose the correct form: “The scheduling team {{blank}} missed visits each week.”','L1.2','language.grammar.subject_verb_agreement',[('a','track',"The singular subject 'team' is treated as one unit here."),('b','tracks',''),('c','have tracked',"This changes the intended present-time statement and uses plural agreement."),('d','were tracking',"This changes both tense and agreement.")],'b',"'Team' is singular in this sentence and takes 'tracks'.","Find the true subject before choosing the verb."),
q('q2','Choose the clearest revision: “When the clinic updated the reminder and the schedule, it confused some patients.”','L1.3','language.pronoun.reference',[('a','When the clinic updated the reminder and the schedule, it confused some patients.',"'It' could refer to the clinic, reminder, schedule, or change."),('b','Updating both the reminder and the schedule confused some patients.',''),('c','When it updated them, it confused some patients.',"The pronouns make the reference less clear."),('d','The clinic updated it and the schedule, which confused it.',"The pronouns remain ambiguous.")],'b',"The revision names the action that caused confusion and removes the ambiguous pronoun.","If several nouns could be the antecedent, rewrite instead of forcing a pronoun."),
q('q3','Choose the most concise revision: “The clinic will continue the pilot for a period of eight additional weeks.”','L1.8','language.style.concision',[('a','The clinic will continue the pilot for eight more weeks.',''),('b','The clinic will continue the pilot for a period of eight additional weeks.',"'For a period of' and 'additional' add length without needed meaning."),('c','The clinic will continue onward with the pilot for a time period of eight more weeks.',"'Continue onward' and 'time period' are redundant."),('d','For the purpose of continuation, the clinic will continue the pilot eight additional weeks.',"This adds abstract wording and repeats 'continue'.")],'a',"The revision preserves the exact duration in fewer words.","Cut repeated or inflated phrases while preserving dates, conditions, and limits."),
q('q4','The pilot showed fewer missed visits; {{blank}}, managers say the test was too short for a firm conclusion.','L1.9','language.transitions.logic',[('a','therefore',"The caution is not a result that follows from fewer missed visits."),('b','however',''),('c','for example',"The managers' caution is not an example of fewer missed visits."),('d','similarly',"The second idea limits the first rather than repeating a similar point.")],'b',"'However' correctly introduces a limitation on the encouraging result.","Use a contrast transition when the second idea qualifies the first."),
q('q5','Choose the correct punctuation: “The clinic tracks three outcomes {{blank}} missed visits, cancellations, and opt-outs.”','L2.4','language.punctuation.colon',[('a',':',''),('b',';',"The words after the blank form a list, not an independent clause."),('c',',',"A colon more clearly introduces the announced list after the complete clause."),('d','.',"A period would leave the list as a fragment.")],'a',"The complete clause announces a list, so a colon correctly introduces it.","Use a colon after a complete clause that introduces examples or a list."),
q('q6','Choose the correct form: “Patients can update {{blank}} contact information online.”','L1.1','language.usage.confused_words',[('a','there',"'There' refers to location."),('b',"they're","'They're' means 'they are'."),('c','their',''),('d','theirs',"'Theirs' cannot directly modify the noun 'contact information'.")],'c',"'Their' shows possession before the noun phrase 'contact information'.","Check what job the word performs in the sentence rather than relying on sound."),
],['editing_passage','workplace','health'],'L1.2',['L1.3','L1.8','L1.9','L2.4','L1.1'])

add_mixed('p-rla-lang-mixed-makerspace','set-rla-lang-mixed-makerspace','A Safer Makerspace Check-In','''
The downtown library recently changed the check-in process for its makerspace, a room where visitors can use tools such as sewing machines, soldering stations, and small cutting devices. Previously, new users watched a general safety video and then signed a form before entering. Staff members noticed that some visitors still had questions about the specific equipment they planned to use.

Under the new process, first-time users watch the same general video but also complete a short equipment check with a staff member. The staff member asks the visitor to identify emergency stops, describe one safe operating step, and show where protective equipment is stored. Returning users do not repeat the full check unless they choose a different type of equipment or have not visited for six months.

The library tested the process for four weeks. During that time, staff recorded fewer cases in which users began setting up a machine incorrectly. However, the average check-in time for first-time visitors increased by about six minutes. Some visitors said the extra review made them more confident, while others said the process felt repetitive after they had already watched the video.

Library managers plan to keep the procedure for another two months while collecting more information. They want the written instructions to explain who needs the extra check, when it must be repeated, and why the library is testing the change. The instructions should not imply that the pilot has eliminated all safety problems. They should also avoid long, overloaded sentences because users may read them while waiting at the front desk.
''','community',[
q('q1','Choose the parallel revision: “Users must identify the stop button, describing one safety step, and show the protective equipment.”','L1.6','language.parallelism.structure',[('a','Users must identify the stop button, describe one safety step, and show the protective equipment.',''),('b','Users must identifying the stop button, describe one safety step, and showing the protective equipment.',"The verb forms do not match."),('c','Users must identify the stop button, a safety step description, and show the protective equipment.',"The middle item is a noun phrase rather than a verb."),('d','Users must identify the stop button, describing one safety step, and the protective equipment is shown.',"The list mixes verb forms and voice.")],'a',"All three actions use parallel base verbs after 'must'.","Keep items with the same function in the same grammatical form."),
q('q2','Choose the best revision: “After watching the video, the equipment check was completed by each visitor.”','L1.5','language.modifiers.dangling',[('a','After watching the video, each visitor completed the equipment check.',''),('b','After watching the video, the equipment check was completed by each visitor.',"The opening phrase makes the check appear to watch the video."),('c','The equipment check, after watching the video, completed each visitor.',"The check cannot perform the action of completing visitors."),('d','Watching the video, each equipment check was completed.',"The modifier still lacks the person who watched the video.")],'a',"'Each visitor' now directly follows the phrase describing who watched the video.","Make the noun after an introductory modifier the logical doer of the action."),
q('q3','Choose the correct standard usage: “Returning users do not {{blank}} to repeat the full check every visit.”','L1.4','language.usage.standard_usage',[('a','have', ''),('b','got',"'Do not got to' is not standard English."),('c','gotta',"'Gotta' is informal speech and does not fit the formal instructions."),('d','having',"After 'do not,' use the base verb, not the -ing form.")],'a',"'Do not have to' is the standard construction for lack of requirement.","In formal editing, replace speech forms with clear standard constructions."),
q('q4','Choose the correct possessive: “The {{blank}} instructions are posted beside each machine.”','L2.3','language.possessives.apostrophes',[('a',"machine's",''),('b','machines',"This is plural and does not show that the instructions belong to one machine."),('c',"machines'", "This shows possession by multiple machines, but the sentence refers to each machine individually."),('d',"machine's'", "A singular possessive does not take a second apostrophe.")],'a',"For one machine, the possessive form is machine's.","Decide singular/plural first, then form the possessive."),
q('q5','Choose the best sentence boundary: “Check-in takes longer now {{blank}} staff are still collecting feedback.”','L2.4','language.punctuation.clauses',[('a',', and',''),('b',',',"A comma alone creates a splice between two independent clauses."),('c',';',"A semicolon would be grammatically possible only if the second clause did not need the intended additive connection; the test asks for the clearest relationship stated by the draft."),('d',':',"The second clause is not a list or explanation introduced by the first.")],'a',"A comma plus 'and' joins the two complete, related statements and preserves the additive relationship.","Use punctuation together with a connector when the logic between independent clauses matters."),
q('q6','Choose the correct capitalization.','L2.1','language.capitalization.mechanics',[('a','The Downtown Library tested the process in April.',"If 'downtown library' is a generic description rather than the institution's formal name, it should remain lowercase."),('b','The downtown library tested the process in April.',''),('c','The downtown library tested the process in april.',"Months are capitalized."),('d','The downtown Library tested the process in April.',"A common noun is not capitalized simply because it names a place.")],'b',"The location description is generic, while the month 'April' is a proper name.","Capitalize official names and calendar names, not common nouns for emphasis."),
],['editing_passage','community','workplace'],'L1.6',['L1.5','L1.4','L2.3','L2.4','L2.1'])

add_mixed('p-rla-lang-mixed-garden','set-rla-lang-mixed-garden','Coordinating the Community Garden','''
The Oak Street Community Garden is preparing for its busiest planting weekend of the year. More than sixty volunteers have registered for Saturday, and several local organizations are donating tools, soil, and seedlings. The volunteer coordinator is revising a message that explains arrival times, work groups, and what participants should bring.

Volunteers will check in at the north gate between 8:30 and 9:00 a.m. After checking in, each person will receive a colored card showing a work area. Green cards are for the vegetable beds, blue cards are for the rain garden, and yellow cards are for the tool-cleaning station. The coordinator asks volunteers to bring a refillable water bottle, closed shoes, and sun protection.

The garden has enough hand tools for most tasks, but volunteers who own work gloves are encouraged to bring them. A small number of wheelbarrows will be shared among the groups. Because the site has narrow paths, the coordinator does not want volunteers to leave bags or personal items beside the beds. A storage tent near the entrance will be available throughout the morning.

The message also explains what happens if heavy rain begins before the event. Organizers will post a decision on the garden website by 7:00 a.m. Saturday. If the event is delayed, registered volunteers will also receive an email. The coordinator wants the final message to be friendly, but it must still use standard English and make every instruction easy to follow on a phone screen.
''','community',[
q('q1','Choose the correct form: “Each of the volunteers {{blank}} a colored work card.”','L1.7','language.grammar.complex_agreement',[('a','receive',"'Each' is singular even though 'volunteers' is plural."),('b','receives',''),('c','have received',"This plural verb phrase does not agree with 'each'."),('d','were receiving',"This changes tense and agreement.")],'b',"The subject 'each' is singular and takes 'receives'.","Do not let a plural noun inside an of-phrase control the verb."),
q('q2','Choose the clearest pronoun revision: “When volunteers put bags beside the beds, they can block the paths.”','L1.3','language.pronoun.reference',[('a','When volunteers put bags beside the beds, they can block the paths.',"'They' could refer to the volunteers or the bags."),('b','Bags left beside the beds can block the paths.',''),('c','When they put them beside them, they can block the paths.',"The repeated pronouns make the sentence much less clear."),('d','The paths can block them when volunteers put bags beside the beds.',"This reverses the logical relationship.")],'b',"The revision names 'bags' as the things that can block the paths.","Replace a pronoun when two possible antecedents could change the meaning."),
q('q3','Choose the correct sentence:','L2.2','language.boundaries.fragments_runons',[('a','If heavy rain begins before the event.',"This dependent clause is a fragment."),('b','If heavy rain begins before the event, organizers will post an update.',''),('c','If heavy rain begins before the event, and.',"The main clause is missing."),('d','Because heavy rain begins. Organizers will post an update.',"The first sentence is a dependent-clause fragment.")],'b',"The conditional clause is attached to a complete main clause.","An if-clause needs a main clause to complete the thought."),
q('q4','Choose the most concise revision: “Volunteers who have their own personal work gloves may bring them.”','L1.8','language.style.concision',[('a','Volunteers with work gloves may bring them.',''),('b','Volunteers who have their own personal work gloves may bring them.',"'Own personal' is redundant, and 'who have' can be shortened here."),('c','Volunteers personally owning their own gloves may bring those gloves themselves.',"This adds repeated ownership and unnecessary words."),('d','In the event that volunteers possess gloves personally, they may bring them.',"This is inflated and less direct.")],'a',"The sentence keeps the permission and item while removing redundant wording.","Remove repeated ownership words and unnecessary phrases."),
q('q5','The paths are narrow; {{blank}}, bags should be stored in the entrance tent.','L1.9','language.transitions.logic',[('a','therefore',''),('b','however',"The storage instruction is a result of the narrow paths, not a contrast."),('c','for example',"The storage rule is not an example of narrow paths."),('d','meanwhile',"The relationship is cause/result, not simultaneous timing.")],'a',"'Therefore' shows that the storage rule follows from the narrow-path condition.","Choose the transition after naming the relationship in plain words."),
q('q6','Choose the correct possessive: “The {{blank}} website will post the rain decision.”','L2.3','language.possessives.apostrophes',[('a',"garden's",''),('b','gardens',"This plural form does not show possession."),('c',"gardens'", "This would mean the website belongs to multiple gardens."),('d',"garden's'", "A singular possessive takes only apostrophe + s.")],'a',"One garden owns or operates the website, so garden's is correct.","For one owner, use singular noun + apostrophe + s."),
],['editing_passage','community'],'L1.7',['L1.3','L2.2','L1.8','L1.9','L2.3'])

add_mixed('p-rla-lang-mixed-warehouse','set-rla-lang-mixed-warehouse','Improving the Warehouse Handoff','''
A regional warehouse is testing a new handoff procedure between the day and evening shifts. In the old system, supervisors often left handwritten notes on a clipboard near the loading area. Those notes varied in detail, and evening staff sometimes had to search for information about delayed trucks, damaged packages, or equipment that needed attention.

The new procedure uses a short digital form. Before leaving, the day supervisor records any unfinished loading tasks, notes equipment problems, and identifies deliveries that are expected after 5 p.m. The evening supervisor reviews the form at the beginning of the shift and can add questions before the day supervisor leaves. Urgent safety issues must still be reported directly by phone rather than only entered in the form.

During a two-week trial, managers found that fewer evening workers asked where unfinished tasks had been recorded. However, the form also created a new problem: some supervisors entered long paragraphs that were difficult to scan quickly. The operations manager therefore asked the team to revise the form so that routine updates use short labeled fields, while unusual problems still allow a brief explanation.

The written procedure must make the sequence clear and distinguish required steps from suggestions. It should also explain that the digital form supports the handoff but does not replace immediate communication for serious safety concerns. Because employees from several departments will use the procedure, the final version needs consistent sentence structure, precise word order, and punctuation that separates instructions cleanly.
''','workplace',[
q('q1','Choose the parallel revision: “The supervisor records unfinished tasks, equipment problems, and which deliveries are late.”','L1.6','language.parallelism.structure',[('a','The supervisor records unfinished tasks, equipment problems, and late deliveries.',''),('b','The supervisor records unfinished tasks, problems with equipment, and which deliveries are late.',"The third item is a clause while the first two are noun phrases."),('c','The supervisor records unfinished tasks, equipment problems, and identifying late deliveries.',"The final item changes to a gerund phrase."),('d','The supervisor records unfinished tasks, equipment problems, and deliveries are late.',"The final item becomes an independent clause.")],'a',"All three items are parallel noun phrases naming what the supervisor records.","Keep items in a list in matching grammatical forms."),
q('q2','Choose the best modifier placement: “Supervisors should only use the phone for urgent safety problems.”','L1.5','language.modifiers.limiting_words',[('a','Only supervisors should use the phone for urgent safety problems.',"This says no one except supervisors may use the phone, which changes the intended limitation."),('b','Supervisors should use the phone only for urgent safety problems.',''),('c','Supervisors only should use the phone for urgent safety problems.',"This awkward placement can imply a contrast with other actions rather than limiting the reason for phone use."),('d','Supervisors should use only the phone for urgent safety problems.',"This says the phone is the only tool they may use, not that phone use is limited to urgent problems.")],'b',"'Only' sits directly before the purpose it limits: urgent safety problems.","Place only beside the word or phrase you intend to restrict."),
q('q3','Choose the correct sentence boundary: “The form is useful {{blank}} it does not replace urgent phone calls.”','L2.4','language.punctuation.clauses',[('a',', but',''),('b',',',"A comma alone creates a splice between two complete clauses."),('c','because',"'Because' would say the form is useful for the reason that it does not replace calls, which is not the intended contrast."),('d',':',"The second clause is a contrast, not an explanation introduced by a colon.")],'a',"A comma plus 'but' correctly joins the two independent clauses and shows contrast.","Use punctuation and conjunctions together to show the relationship between complete clauses."),
q('q4','Choose the most concise revision: “The form contains fields that are labeled with labels for routine updates.”','L1.8','language.style.concision',[('a','The form contains labeled fields for routine updates.',''),('b','The form contains fields that are labeled with labels for routine updates.',"'Labeled with labels' repeats the same idea."),('c','The form has fields which have labels that label routine updates.',"The revision repeats 'label' and remains wordy."),('d','Routine updates are in fields having labeling labels on the form.',"This is awkward and less clear.")],'a',"'Labeled fields' expresses the same information directly.","Turn repeated noun/verb phrases into one precise modifier when meaning is preserved."),
q('q5','Choose the clearest standard sentence.','L1.4','language.usage.standard_usage',[('a','Supervisors gotta fill out the form before they leave.',"'Gotta' is informal speech and not appropriate for a formal procedure."),('b','Supervisors must complete the form before leaving.',''),('c','Supervisors should of completed the form before leaving.',"'Should of' is nonstandard for 'should have'."),('d','Supervisors be completing the form before leaving.',"This construction is not standard for the intended instruction.")],'b',"The sentence uses clear standard English and states the requirement directly.","Formal procedures should use standard forms without slang or speech spellings."),
q('q6','Choose the correct verb: “The list of delayed trucks {{blank}} updated before each shift change.”','L1.2','language.grammar.subject_verb_agreement',[('a','are',"'Trucks' is inside an of-phrase; the subject is singular 'list'."),('b','is',''),('c','have been',"This plural verb phrase does not agree with 'list'."),('d','were',"This plural past-tense verb does not match the singular subject.")],'b',"The singular subject 'list' takes the singular verb 'is'.","Ignore nouns inside an of-phrase when locating the subject."),
],['editing_passage','workplace'],'L1.6',['L1.5','L2.4','L1.8','L1.4','L1.2'])

add_mixed('p-rla-lang-mixed-energy','set-rla-lang-mixed-energy','Reporting a School Energy Audit','''
Students in an environmental science class completed a month-long energy audit of their school building. The project was not designed to produce a complete engineering study. Instead, the class wanted to identify simple patterns that could guide future questions about electricity use.

Teams recorded whether classroom lights and projectors were left on during lunch, after classes, and during several weekend activities. They also reviewed monthly electricity bills from the previous year. The students found that unnecessary lighting was common in a few hallways and shared rooms, but the billing records did not allow them to determine exactly how much electricity those lights used by themselves.

The class prepared a short report for the school administration. The report recommends clearer shutdown reminders and a two-month trial in which selected rooms are checked at the end of each day. Students suggest comparing those observations with the same period from the previous year, while also recording major schedule changes that might affect electricity use.

The teacher reminded students not to claim that the audit proved a particular cause of the school’s total energy use. Weather, air-conditioning demand, weekend events, and equipment changes can all influence the monthly bill. The report therefore separates what students directly observed from what they still need to test. Before publication, the class is editing the report for concise wording, clear pronoun references, correct capitalization, and punctuation that helps readers follow the limits of the evidence.
''','school',[
q('q1','Choose the correct capitalization.','L2.1','language.capitalization.mechanics',[('a','The Environmental Science class reviewed bills from March.',"A school subject used generically is usually lowercase unless it is a language or part of a formal course title."),('b','The environmental science class reviewed bills from March.',''),('c','The environmental science class reviewed bills from march.',"Months are capitalized."),('d','The Environmental science class reviewed bills from March.',"The generic subject phrase should not be partly capitalized.")],'b',"The generic subject name is lowercase; the month 'March' is capitalized.","Capitalize proper names and calendar names, not ordinary school subjects used generically."),
q('q2','Choose the clearest pronoun revision: “The class compared the bills with the schedule because it had changed.”','L1.3','language.pronoun.reference',[('a','The class compared the bills with the schedule because it had changed.',"'It' could refer to the class, bill set, or schedule."),('b','Because the schedule had changed, the class compared it with the bills.',''),('c','The class compared them with it because it changed.',"The pronouns do not identify the intended nouns clearly."),('d','It changed, so it compared the bills with the schedule.',"Both instances of 'it' lack a clear antecedent.")],'b',"The revision names the changed item, 'schedule,' and keeps the later pronoun reference clear.","When a pronoun could point to multiple nouns, name the intended noun."),
q('q3','Choose the correct possessive: “The {{blank}} report separates observations from conclusions.”','L2.3','language.possessives.apostrophes',[('a',"students'",''),('b',"student's", "This shows possession by one student rather than the group."),('c','students',"The plural noun does not show possession of the report."),('d',"students's", "A regular plural ending in s takes only an apostrophe for possession.")],'a',"The report belongs to multiple students, so the plural possessive is students'.","For a regular plural ending in s, add only an apostrophe."),
q('q4','Choose the most concise revision: “The report makes a recommendation that the school should conduct a two-month trial.”','L1.8','language.style.concision',[('a','The report recommends a two-month trial.',''),('b','The report makes a recommendation that the school should conduct a two-month trial.',"'Makes a recommendation that' can be replaced by the direct verb 'recommends'."),('c','The report gives a recommendation in regard to the conducting of a two-month trial.',"This turns a direct action into several abstract noun phrases."),('d','A recommendation is made by the report for the purpose of a two-month trial.',"The passive wording is longer and less direct.")],'a',"The direct verb 'recommends' preserves the meaning in far fewer words.","Prefer strong direct verbs over noun-heavy phrases when no nuance is lost."),
q('q5','The class observed lights left on; {{blank}}, the billing records cannot show how much those lights alone cost.','L1.9','language.transitions.logic',[('a','however',''),('b','therefore',"The limitation is not a result proving a cost figure."),('c','for example',"The billing limitation is not an example of observing lights left on."),('d','similarly',"The two statements have different roles; the second limits the first.")],'a',"'However' introduces the important limitation on what the observation can establish.","Use contrast transitions to signal a limit, exception, or difference."),
q('q6','Choose the correctly punctuated sentence.','L2.4','language.punctuation.clauses',[('a','Several factors can affect the bill: weather, events, and equipment changes.',''),('b','Several factors can affect: the bill, weather, events, and equipment changes.',"The colon incorrectly interrupts the verb and its object."),('c','Several factors can affect the bill; weather, events, and equipment changes.',"A semicolon does not introduce a simple list fragment."),('d','Several factors can affect the bill, weather, events, and equipment changes.',"The comma does not clearly signal that the following items are examples of the factors.")],'a',"The complete clause introduces a list, so the colon is appropriate.","Place a colon after a complete statement, not between a verb and its object."),
],['editing_passage','school','informational'],'L2.1',['L1.3','L2.3','L1.8','L1.9','L2.4'])

add_mixed('p-rla-lang-mixed-transit','set-rla-lang-mixed-transit','Revising the Lost-and-Found Policy','''
The MetroLink transit office is revising its lost-and-found policy after riders complained that the old instructions were difficult to follow. The previous webpage listed several phone numbers, but it did not clearly explain which office handled items found on buses, which office handled items from train stations, or how long property would be stored.

Under the revised process, all reports begin with one online form. Riders describe the missing item, provide the route or station if known, and choose a preferred contact method. Staff members then compare the report with items delivered to the central property office. Items containing identification, such as wallets or student cards, receive priority because staff may be able to contact the owner directly.

Most ordinary property will be stored for thirty days. Certain items, including food, unsafe materials, and objects that cannot be stored securely, may be handled differently. The transit office will publish a separate list of exceptions so that the main policy remains readable. Riders should not travel to the property office until staff confirm that a likely match has been found.

The communications team wants the final policy to sound direct and neutral. It should use standard English, distinguish clearly between required steps and optional suggestions, and avoid sentences in which a modifier could attach to the wrong noun. Editors are also checking agreement in sentences with long prepositional phrases and punctuation in sentences that combine several conditions. The goal is a policy that can be understood quickly without leaving out limits that matter to riders.
''','civics',[
q('q1','Choose the correct verb: “The list of storage exceptions {{blank}} on a separate page.”','L1.7','language.grammar.complex_agreement',[('a','appear',"The subject is singular 'list,' not the plural noun 'exceptions'."),('b','appears',''),('c','have appeared',"This plural verb phrase does not agree with 'list'."),('d','were appearing',"This changes tense and uses plural agreement.")],'b',"The true subject is 'list,' so the singular verb 'appears' is correct.","Ignore the noun inside the of-phrase when matching the subject and verb."),
q('q2','Choose the best modifier placement: “Riders should only visit the office after staff confirm a match.”','L1.5','language.modifiers.limiting_words',[('a','Only riders should visit the office after staff confirm a match.',"This says no one except riders may visit, which changes the intended rule."),('b','Riders should visit the office only after staff confirm a match.',''),('c','Riders only should visit the office after staff confirm a match.',"This awkward placement can change what 'only' limits."),('d','Riders should visit only the office after staff confirm a match.',"This limits the destination rather than the timing.")],'b',"'Only' directly limits the timing condition: after confirmation.","Place limiting modifiers beside the exact word or phrase they restrict."),
q('q3','Choose the standard revision: “Riders should of completed the form before calling.”','L1.4','language.usage.standard_usage',[('a','Riders should have completed the form before calling.',''),('b','Riders should of completed the form before calling.',"'Should of' is a nonstandard spelling of the spoken contraction 'should've'."),('c','Riders should had completed the form before calling.',"A modal cannot be followed by 'had' in this construction."),('d','Riders should completing the form before calling.',"A modal requires the base verb or have + participle, not the -ing form.")],'a',"'Should have completed' is the standard modal-perfect form.","If you hear 'should've,' write 'should have,' not 'should of'."),
q('q4','Choose the correct punctuation: “The form asks for three details {{blank}} the item, the route or station, and a contact method.”','L2.4','language.punctuation.colon',[('a',':',''),('b',';',"A semicolon cannot introduce this list fragment."),('c',',',"A colon more clearly introduces the announced list."),('d','.',"A period would leave the list as a fragment.")],'a',"The complete clause announces three details, so a colon correctly introduces them.","Use a colon after a complete clause that sets up a list."),
q('q5','Choose the clearest concise revision: “Staff members will make a comparison between the report and the items received.”','L1.8','language.style.concision',[('a','Staff members will compare the report with received items.',''),('b','Staff members will make a comparison between the report and the items received.',"'Make a comparison between' can be replaced by the direct verb 'compare'."),('c','A comparison will be made by staff members between the report and the items received.',"The passive form is longer without adding meaning."),('d','Staff members will perform the process of comparison between reports and received items.',"This adds unnecessary abstract wording.")],'a',"The direct verb 'compare' expresses the same action more efficiently.","Prefer a direct verb when a noun phrase only repeats that verb's meaning."),
q('q6','Choose the correct word: “Staff may contact riders if an item contains {{blank}} identification.”','L1.1','language.usage.confused_words',[('a','personal',''),('b','personnel',"'Personnel' refers to employees or staff, not information identifying a person."),('c','personally',"An adverb cannot directly modify the noun 'identification' this way."),('d','person',"The noun 'person' does not form the intended adjective phrase.")],'a',"'Personal identification' means identification connected to an individual person.","Use context and part of speech to separate commonly confused words."),
],['editing_passage','civics','workplace'],'L1.7',['L1.5','L1.4','L2.4','L1.8','L1.1'])

print('Generated Language focused and mixed source JSON.')
