import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'content-src'/'er-prompts'; OUT.mkdir(parents=True,exist_ok=True)

def model(title, winner, r1, e1, r2, e2, weakness):
    other='B' if winner=='A' else 'A'
    weakness = weakness.strip().rstrip('.!?')
    return f'''Both sources address the same policy question, but Source {winner} presents the better-supported argument. Its position is stronger for two main reasons: {r1}; and {r2}. Source {other} raises a relevant concern, but the support behind that concern is less complete.

First, Source {winner} is stronger because {r1}. It reports that {e1}. This evidence matters because it directly addresses a central factual question behind the recommendation rather than asking the reader to accept a prediction. The evidence also fits the scope of the claim, which makes the reasoning easier to evaluate. Source {other} does not provide equally specific support on this point.

Source {winner} is also stronger because {r2}. It explains that {e2}. This matters because the source considers another important part of the decision instead of relying on a single favorable fact. {weakness}. That concern is relevant, but the weaker source does not show that it outweighs Source {winner}'s more direct evidence or that the proposed response would fail.

Overall, Source {winner} is better supported because its recommendation is tied to specific evidence and its reasoning stays within the limits of that evidence. Source {other} contributes a useful caution, but Source {winner} gives the reader clearer grounds for judging likely results.'''

def prompt(id,title,topic,a_title,a_text,b_title,b_text,stronger,reasons,evidence,weakness):
    m=model(title,stronger,reasons[0],evidence[0],reasons[1],evidence[1],weakness)
    return {
      'schemaVersion':1,'id':id,'title':title,'topic':topic,'status':'published','version':1,'author':'Chee Skool','reviewer':'Extended Response V1 editorial review',
      'prompt':'Analyze both sources. Determine which argument is better supported by relevant evidence and reasoning. Use specific evidence from the sources to support your response.',
      'sourceA':{'title':a_title,'text':a_text,'attribution':'Original content by Chee Skool'},
      'sourceB':{'title':b_title,'text':b_text,'attribution':'Original content by Chee Skool'},
      'strongerSource':stronger,
      'authoringKey':{'reasons':reasons,'evidence':evidence,'weakerSourceLimitation':weakness},
      'modelResponse':m,
      'annotations':[
        {'label':'Thesis','note':f'The response clearly identifies Source {stronger} as better supported and previews two reasons.'},
        {'label':'Evidence','note':'Specific source evidence is used rather than personal experience or outside facts.'},
        {'label':'Analysis','note':'The response explains why the evidence matters instead of only repeating it.'},
        {'label':'Comparison','note':'The weaker source is treated fairly, but its evidentiary or reasoning limitation is identified.'},
        {'label':'Organization','note':'Each body paragraph develops one reason before the conclusion restates the judgment.'}
      ],
      'revisionPrompts':[
        'Where did I clearly state which source is better supported?',
        'Where did I explain why a piece of evidence matters instead of only summarizing it?',
        'Did I evaluate both sources fairly and identify a specific weakness in the weaker argument?',
        'Did I preserve qualifiers such as may, could, some, or limited when the source used them?'
      ]
    }

prompts=[]

prompts.append(prompt('er-weekend-bus','Should the Weekend Bus Pilot Expand?','transportation',
'Expand the Pilot Carefully', '''A transit agency tested 20-minute Saturday service on two busy routes for four months. Average Saturday ridership on those routes increased 17 percent compared with the same months the previous year, while on-time performance remained within two percentage points of the weekday average. A rider survey of 860 passengers found that 38 percent used the added trips for work and 27 percent for medical appointments or errands. The agency estimates that expanding the schedule to four additional routes would cost $420,000 per year. It proposes a one-year expansion only on routes where weekend buses regularly reach at least 70 percent of seated capacity.\n\nThe agency also reports an important limitation. Fuel prices were lower during part of the pilot, and two large community events may have increased ridership on several weekends. For that reason, the proposal does not claim that every route needs more service. Instead, it recommends using passenger counts, missed-trip reports, and transfer connections to select the next routes. If the additional routes do not meet the ridership threshold after one year, the agency says the schedule can be reduced again.''',
'Improve Reliability Before Adding Trips', '''A drivers' association argues that the transit agency should first improve reliability on the current weekend schedule. Its members report that traffic near shopping districts often delays buses and causes missed transfers. The association notes that some riders may value a bus that arrives consistently more than a bus that comes more often. It recommends adding recovery time at route endpoints and assigning standby drivers during the busiest weekend periods.\n\nThe association points to 74 written rider complaints collected over six months that mention late buses or missed connections. However, the complaints cover the entire bus network, not only the two pilot routes, and the letter does not state how many total weekend trips were operated during the period. The association also does not estimate the cost of its proposed staffing changes. It agrees that some routes may eventually need more frequent service, but argues that the agency should solve reliability problems before committing to a larger expansion.''','A',
['it uses measured ridership, on-time performance, survey results, and a defined expansion threshold','it acknowledges confounding factors and proposes a reversible one-year test'],
['ridership rose 17 percent while on-time performance stayed close to the weekday average','the agency limits expansion to routes meeting a capacity threshold and says service can be reduced if results are weak'],
'Source B cites real complaints, but the complaints are network-wide and are not placed in context with total trips or costs.'))

prompts.append(prompt('er-solar-roofs','Should the City Fund Solar Panels on Public Buildings?','renewable energy',
'Install Solar on All Major Buildings Now', '''A city council member proposes installing solar panels on every major municipal building within two years. She argues that the city spends too much on electricity and that solar power would demonstrate environmental leadership. Her office cites one recreation center where a small rooftop array produced about 22 percent of the building's annual electricity use. She also notes that panel prices have fallen over the past decade and that state incentives may reduce installation costs.\n\nThe proposal estimates that a citywide program could save money over time, but it does not include roof-by-roof engineering assessments or a full financing plan. Several buildings are more than forty years old, and the proposal assumes that most roofs can support panels without major structural work. The council member says delaying action would miss available incentives and argues that the city should approve the full program while engineers complete detailed designs.''',
'Start with Audited Buildings and Publish Results', '''The city facilities director supports solar power but recommends a staged program. Her department inspected twelve large public buildings and found that five have roofs expected to need replacement within six years. Installing panels on those roofs now could require removing and reinstalling the equipment during roof work. For the remaining seven buildings, engineers estimated annual solar output using roof area, shade, and electricity records. Three sites could offset more than 30 percent of current use, while two heavily shaded sites would offset less than 10 percent.\n\nThe director proposes beginning with the three strongest sites. A financing analysis estimates a combined installation cost of $1.8 million after incentives and an expected simple payback of about eleven years under current electricity prices. She cautions that future prices and maintenance costs could change that estimate. The plan would publish actual energy production and maintenance data for two years before the city decides whether to expand to the remaining buildings.''','B',
['it uses building-specific engineering and energy estimates rather than assuming all roofs are equally suitable','it matches the scale of its recommendation to uncertainty by starting with the strongest sites and measuring results'],
['five of twelve roofs are expected to need replacement soon, while projected solar offsets vary widely by site','the plan includes a cost estimate, an eleven-year payback estimate, and a two-year measurement period before expansion'],
'Source A provides a useful example and notes incentives, but it generalizes from one building and lacks roof-specific feasibility and financing evidence.'))

prompts.append(prompt('er-inspection-automation','Should the Factory Expand Automated Visual Inspection?','workplace automation',
'Expand with Human Review', '''A factory tested an automated camera system on one packaging line for sixteen weeks. Before the pilot, final inspectors found an average of 31 labeling or seal defects per 10,000 units. During the pilot, the camera flagged suspect packages earlier in the line, and final-inspection defects fell to 19 per 10,000 units. The system also produced false alarms on about 1.8 percent of packages, so workers still reviewed flagged items before removal.\n\nThe quality team recommends adding the system to two similar lines while keeping human review. It estimates equipment and integration costs of $260,000 and says the company should compare avoided rework, downtime, and false alarms for six additional months. The team does not claim the cameras can replace inspectors. Instead, it argues that the pilot shows the system may help workers find certain repetitive visual defects sooner.''',
'Keep Inspection Fully Manual', '''A senior inspector argues that automated cameras should not be expanded because experienced workers notice problems that a programmed system may miss. He gives examples of slightly unusual package sounds and material texture changes that have sometimes revealed equipment problems before a visible defect appeared. He also notes that false alarms can slow production if workers must repeatedly stop to check acceptable packages.\n\nThe inspector recommends spending the money on additional training and preventive maintenance instead. He cites two past equipment failures that were first noticed by workers rather than by automated sensors. However, those failures occurred before the camera pilot and involved mechanical problems outside the system's stated visual-inspection purpose. He does not compare the cost of additional staff training with the proposed camera expansion or address the decline in final labeling and seal defects during the pilot.''','A',
['it directly measures the defect category the camera system is designed to detect','it explicitly retains human review and proposes another limited expansion to test costs and false alarms'],
['final labeling and seal defects fell from 31 to 19 per 10,000 units during the pilot','the quality team records a 1.8 percent false-alarm rate and recommends continued human review rather than replacement'],
'Source B makes a strong case for human judgment on broader mechanical problems, but those examples do not directly test the camera system’s visual-defect performance.'))

prompts.append(prompt('er-phone-policy','Should the High School Adopt a Full-Day Phone Ban?','school policy',
'Adopt a Full-Day Ban', '''A parent committee proposes requiring students to store phones in locked pouches from first bell to dismissal. The committee says teachers report frequent distraction and that students need clearer boundaries. It cites a survey in which 64 percent of 42 responding teachers said phones interrupted instruction at least several times per week. The committee also points to one neighboring school that adopted locked pouches and reported fewer classroom phone violations after implementation.\n\nThe proposal does not include student survey data, emergency-access procedures, or information about how the neighboring school handled lunch and free periods. It assumes that a single rule will be easier to enforce than teacher-by-teacher policies. The committee acknowledges that purchasing pouches would cost about $28,000 but argues that reduced distraction justifies the expense.''',
'Use a Class-Time Restriction with Measured Exceptions', '''The principal proposes a narrower rule: phones must remain silent and stored during instructional periods, but students may use them during lunch and designated breaks. The school tested this approach for nine weeks in ten classrooms. Recorded phone-related interruptions fell 46 percent compared with the previous nine weeks. Teachers also logged 23 cases in which students needed temporary access for translation, medical monitoring, or a teacher-directed activity.\n\nThe principal argues that the pilot shows strong improvement without requiring a full-day ban. She recommends schoolwide implementation, a common consequence system, and another semester of data collection. She notes that the pilot covered only ten classrooms and that teachers varied in enforcement, so the results may not transfer perfectly. The plan includes an emergency-contact procedure through the main office and would review whether lunch-period phone use creates separate problems before changing that part of the policy.''','B',
['it provides before-and-after interruption data from a school pilot rather than relying mainly on reported concern','it addresses exceptions and limitations while proposing continued measurement'],
['phone-related interruptions fell 46 percent in the ten-classroom pilot','the plan documents legitimate exceptions and admits that enforcement differences limit generalization'],
'Source A identifies a real distraction problem, but its support for a full-day ban relies heavily on teacher opinion and a neighboring-school example without comparable context.'))

prompts.append(prompt('er-stormwater-fee','Should the City Charge a Stormwater Fee?','environmental regulation',
'Create a Fee Based on Impervious Surface', '''The public works department proposes a stormwater fee based on the amount of roof, parking lot, and other impervious surface on each property. The department reports that three severe storms caused $6.4 million in street and drainage repairs over five years. Engineering models identify 14 drainage projects expected to reduce repeated flooding at intersections and near two schools. The proposed fee would raise about $3.1 million per year and includes credits for properties that install rain gardens, storage tanks, or other systems that reduce runoff.\n\nThe department acknowledges that model estimates cannot predict every storm. It therefore proposes publishing project costs and flood reports annually. Low-income homeowners could receive partial assistance, and large properties could reduce fees through verified runoff controls. The department argues that linking charges to impervious area better reflects how much runoff a property sends into the drainage system than a flat household fee would.''',
'Pay for Drainage from Existing Taxes', '''A taxpayer group opposes a separate stormwater fee. It argues that residents already pay property and sales taxes and that the city should rearrange existing spending instead of creating another bill. The group notes that flood damage varies from year to year and warns that some proposed drainage projects may cost more than expected. It recommends postponing the fee while the city searches for grants and cuts lower-priority projects.\n\nThe group cites a state grant that funded part of a drainage project eight years ago as evidence that outside funding is possible. It does not identify current grants large enough to cover the 14 planned projects or specify which existing programs should be reduced. The group supports runoff-reduction credits if a fee is eventually adopted but argues that the city has not proven a new charge is necessary now.''','A',
['it connects a defined revenue mechanism to documented repair costs and identified projects','it explains how the fee reflects runoff contribution and includes credits and assistance to address fairness concerns'],
['the city recorded $6.4 million in storm-related repair costs and has 14 modeled drainage projects','the proposed fee is tied to impervious surface and allows verified runoff controls to reduce charges'],
'Source B raises a legitimate tax-burden concern, but it does not identify a funded alternative large enough to meet the stated infrastructure need.'))

prompts.append(prompt('er-bridge-plan','Should the County Replace the Harbor Bridge Now?','infrastructure spending',
'Replace the Bridge Immediately', '''A county commissioner argues that the Harbor Bridge should be replaced within three years. The bridge is 63 years old, and recent inspections found corrosion in several steel members. The commissioner says an older bridge will only become more expensive to maintain and that a new structure could include wider bicycle lanes and better storm protection. A preliminary concept places the replacement cost at about $180 million.\n\nThe commissioner points to two emergency repairs during the past decade as evidence that waiting is risky. However, the proposal does not include a current life-cycle cost comparison between replacement and rehabilitation. Engineers have not classified the bridge as unsafe for normal traffic, and the $180 million estimate was prepared before detailed geotechnical work. The commissioner argues that the county should begin final design now so construction can start before conditions become more serious.''',
'Rehabilitate Critical Components and Reassess', '''The county engineering office recommends a staged rehabilitation first. Its latest inspection rates the bridge as structurally adequate but identifies three corrosion zones that need repair within two years. Engineers estimate $24 million for steel replacement, coating, drainage improvements, and new monitoring sensors. A life-cycle analysis estimates that this work could extend reliable service by 12 to 15 years, although unusually rapid corrosion could shorten that period.\n\nThe office does not reject eventual replacement. Instead, it recommends completing the critical repairs, collecting five years of sensor data, and using that information while developing a long-term replacement design. The report also notes that replacing the bridge now would require temporary traffic capacity elsewhere, adding costs that are not included in the preliminary $180 million concept. The staged plan includes annual inspection triggers that would accelerate replacement if deterioration exceeds specified limits.''','B',
['it uses the current engineering condition rating and a specific rehabilitation scope instead of treating age alone as proof of immediate replacement','it provides a life-cycle estimate, monitoring plan, and explicit triggers for changing course'],
['engineers rate the bridge structurally adequate while identifying three repair zones and a $24 million rehabilitation package','the plan estimates 12 to 15 additional years of service and sets inspection thresholds that could accelerate replacement'],
'Source A reasonably emphasizes long-term risk and future design needs, but its immediate-replacement case lacks the same life-cycle and traffic-cost analysis.'))

prompts.append(prompt('er-clinic-reminders','Should the Clinic Expand Text Reminders?','public health policy',
'Expand with Opt-Out and Language Choice', '''A community clinic tested appointment text reminders with 2,400 adult patients for six months. Missed appointments fell from 18 percent in the previous six-month period to 12 percent during the pilot. The clinic also recorded 96 patients who asked not to receive texts and 143 who requested reminders in a language other than English. Staff estimate the messaging service would cost about $14,000 per year if expanded to all adult appointments.\n\nThe clinic recommends expansion with an easy opt-out, language preference settings, and a process for patients who share phones. It notes that the before-and-after comparison does not prove texts caused the entire decline because staffing and scheduling also changed slightly. For that reason, the clinic plans to compare missed-appointment rates by reminder preference during the next year and to keep phone calls available for patients who request them.''',
'Use Phone Calls Instead', '''A patient advisory group argues that phone calls should remain the main reminder method. Members say some older patients are uncomfortable with text messages and that shared phones may create privacy concerns. The group reports hearing from nine patients who missed or misunderstood automated messages during the pilot. It recommends hiring part-time staff to make reminder calls and says a person can answer questions that a text cannot.\n\nThe group does not estimate the staffing cost or report how many patients successfully received texts. It agrees that patients who prefer texts should be allowed to choose them but argues that expansion should wait until the clinic studies privacy and language access more carefully. The group also suggests that any reminder system should verify contact information at each visit.''','A',
['it reports a measurable decline in missed appointments across a large pilot while openly acknowledging other possible causes','it directly addresses opt-out, language, shared-phone, and follow-up measurement concerns'],
['missed appointments fell from 18 percent to 12 percent among a 2,400-patient pilot period','the expansion plan includes opt-out and language settings while keeping alternative phone calls available'],
'Source B raises important accessibility and privacy concerns, but it relies on a small set of reported problems and gives no cost or overall delivery-rate comparison.'))

prompts.append(prompt('er-market-redevelopment','How Should the Old Market Block Be Redeveloped?','community development',
'Build a Large Mixed-Use Complex', '''A development company proposes replacing the aging Old Market buildings with a twelve-story mixed-use complex containing apartments, offices, and retail space. The company says the project would create construction jobs and add 280 housing units near transit. Its economic summary estimates $3.6 million in additional annual property and sales-tax revenue after full occupancy. The developer also promises a public plaza and space for eight current market vendors.\n\nThe proposal requests a $9 million city infrastructure contribution for street, sewer, and plaza work. The economic summary assumes 92 percent residential occupancy within two years but does not include a sensitivity analysis if rents or office demand are weaker. Twenty-two current vendors operate on the block, so most would need to relocate. The company says relocation grants could be discussed later but has not included them in the current budget.''',
'Renovate in Phases and Add Housing Above Existing Shops', '''A local planning coalition proposes renovating the market block in three phases. A structural survey commissioned by the city found that four of the six main buildings can be rehabilitated, while two rear structures should be replaced. The coalition proposes adding four floors of housing above the rehabilitated buildings and constructing a new six-story building on the replacement sites, for an estimated 146 housing units. Its cost plan includes $2.1 million for seismic work, accessibility, and vendor relocation during construction.\n\nThe coalition estimates lower tax revenue than the developer's proposal, but it includes lease assumptions based on current neighborhood rents and a phased financing schedule. The plan reserves below-market commercial leases for 16 existing vendors for five years and includes checkpoints after each phase so later construction can be adjusted if costs rise. The coalition admits that preserving older buildings limits the number of new units and may require longer construction, but argues that the plan balances housing growth with business continuity and lower public financial exposure.''','B',
['it relies on a city structural survey and a detailed phased cost plan rather than assuming the entire block must be replaced','it addresses vendor displacement and financial uncertainty with funded relocation, lease commitments, and decision checkpoints'],
['four of six main buildings are judged suitable for rehabilitation and the plan budgets specific seismic/accessibility work','the proposal funds relocation and preserves below-market leases for 16 vendors while allowing later phases to adjust if costs rise'],
'Source A offers more housing and potentially higher tax revenue, but its occupancy assumptions and vendor-relocation costs are less fully supported.'))

for p in prompts:
    (OUT/f"{p['id']}.json").write_text(json.dumps(p,indent=2,ensure_ascii=False)+'\n')
print('Generated',len(prompts),'ER prompts')
for p in prompts:
    a=len(p['sourceA']['text'].split()); b=len(p['sourceB']['text'].split()); m=len(p['modelResponse'].split())
    print(p['id'],a,b,m,p['strongerSource'])
