import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
PASS=ROOT/'content-src'/'passages'; SETS=ROOT/'content-src'/'sets'
PASS.mkdir(parents=True,exist_ok=True); SETS.mkdir(parents=True,exist_ok=True)

units=[
{
'id':'understand-map-sources','slug':'understand-map-sources','title':'Start by Mapping the Task','skills':['W1.1','W1.2'],
'passage_title':'Should School Start Later?','context':'education',
'text':'''Source A - Later Start Pilot\nA district tested an 8:45 a.m. high-school start for one semester. Attendance improved from 91 to 94 percent, first-period tardiness fell by 28 percent, and student surveys reported more sleep on school nights. The district notes that the pilot included only two schools and recommends testing transportation costs before expanding it.\n\nSource B - Keep the Current Schedule\nA transportation supervisor argues that moving the high-school start time would force some elementary routes to change. She says families value predictable schedules and warns that later dismissal could interfere with sports and after-school jobs. She does not provide cost estimates or attendance data but asks the district to study those effects before changing all schools.'''
},
{
'id':'choose-stronger-argument','slug':'choose-stronger-argument','title':'Judge Support, Not Preference','skills':['W1.3'],
'passage_title':'Should the City Add Refill Stations?','context':'community',
'text':'''Source A - Expand the Refill Program\nThe city installed six public water-refill stations in parks for a twelve-week pilot. Maintenance records show that the stations were used about 18,000 times, and trash audits found 11 percent fewer single-use bottles in the same parks than during the previous summer. The parks department estimates annual maintenance at $9,600 and recommends adding four stations near transit hubs while tracking winter use.\n\nSource B - Spend the Money Elsewhere\nA neighborhood association opposes expansion. Its letter says some residents still buy bottled water and argues that refill stations will not eliminate plastic waste. The letter also states that vandals could damage the machines and that the city has many other needs. It gives no repair records, budget comparison, or evidence about whether the pilot reduced litter.'''
},
{
'id':'thesis-evidence','slug':'thesis-evidence','title':'Build a Thesis and Choose Evidence','skills':['W1.4','W1.5'],
'passage_title':'Should Remote Work Expand?','context':'workplace',
'text':'''Source A - Expand with Training\nA six-month remote-work pilot included 200 employees. Completed projects rose 12 percent and average sick days fell. Seventy-eight percent of participants preferred the flexible schedule. Managers reported some communication delays, so the company recommends training managers and requiring two shared office days before expanding the policy.\n\nSource B - Return to the Office\nA department manager argues that remote work should end because employees may become distracted at home and teamwork could weaken. He says face-to-face communication feels more productive and predicts that performance will decline if the policy expands. He provides no productivity data from the pilot and does not compare the pilot group with office-only employees.'''
},
{
'id':'analyze-not-summarize','slug':'analyze-not-summarize','title':"Analyze, Don't Just Summarize",'skills':['W1.6','W1.7'],
'passage_title':'Can Street Trees Cool a Commercial Block?','context':'environment',
'text':'''Source A - Plant a Test Corridor\nA university team measured afternoon surface temperatures on eight commercial blocks. Blocks with mature tree cover averaged 5 degrees Celsius cooler on sunny days than blocks with little shade. The researchers caution that building height and pavement type also affect temperature. They recommend a one-block tree-planting pilot with temperature monitoring before a larger investment.\n\nSource B - Use Shade Sails Instead\nA business owner argues that trees grow too slowly and says shade sails would provide immediate cover. She points to one cafe patio where a sail lowered the temperature beneath the fabric. She does not report measurements from the rest of the block or compare installation and maintenance costs. She says the city should therefore choose sails for the entire commercial district.'''
},
{
'id':'organize-develop-revise','slug':'organize-develop-revise','title':'Organize, Develop and Revise','skills':['W1.8','W1.9','W1.10','W1.11'],
'passage_title':'Should the Library Keep Sunday Hours?','context':'community',
'text':'''Source A - Keep Sunday Hours\nDuring a three-month Sunday-hours pilot, the downtown library averaged 310 visits each Sunday. Forty-two percent of surveyed Sunday visitors said weekday work or school schedules made other visits difficult. Staffing cost $18,400 for the pilot, and the library proposes keeping Sunday hours while reducing one lightly used weekday evening shift.\n\nSource B - Restore the Old Schedule\nA budget committee member argues that the library should close on Sundays because the city should avoid adding service costs. She notes that digital materials are available every day and says residents can plan visits during existing hours. She does not compare the proposed shift reduction with Sunday staffing costs or provide data on whether Sunday visitors use digital materials instead.'''
},
{
'id':'full-extended-response','slug':'full-extended-response','title':'Plan the Full Response','skills':['W1.12'],
'passage_title':'Should Apartments Join Food-Waste Collection?','context':'public_policy',
'text':'''Source A - Expand Collection to Apartments\nA city pilot collected food scraps from 1,100 apartment households for six months. Participating buildings sent 19 percent less trash to the landfill, and contamination in the food-waste bins fell from 14 percent to 6 percent after clearer signs were installed. The sanitation department recommends expanding gradually and providing building managers with training.\n\nSource B - Delay Expansion\nA property association argues that apartment collection should wait. It says some buildings have little space for extra bins and that managers may face complaints about odor. The association recommends another year of study but provides no contamination records, cost estimates, or data showing that odor complaints occurred during the pilot. It does suggest testing smaller bins in buildings with limited storage.'''
}
]

sequences={
'understand-map-sources':['b','d','a','c','c','a','d','b'],
'choose-stronger-argument':['c','a','d','b','a','d','b','c'],
'thesis-evidence':['d','b','a','c','b','d','c','a'],
'analyze-not-summarize':['a','c','b','d','c','b','a','d'],
'organize-develop-revise':['b','a','d','c','a','c','d','b'],
'full-extended-response':['d','a','c','b','c','d','b','a'],
}

# Each tuple: skill, family, prompt, correct text, [(wrong text, type, reason)*3], explanation, tip
Q={
'understand-map-sources':[
('W1.1','writing.er.task','What is the core job of the Extended Response task?','Evaluate which source presents the better-supported argument.',[
('Choose the position you personally agree with most.','personal_opinion','The task evaluates source support, not the learner\'s personal preference.'),('Summarize both sources without making a judgment.','summary_only','A summary alone does not answer which argument is better supported.'),('Prove that one source is completely correct.','overstatement','The task asks for evaluation of support, not absolute proof.')],'The response must judge the quality of the supplied arguments using their evidence and reasoning.','Judge the sources, not your personal preference.'),
('W1.2','writing.er.map','Which note best maps Source A?','Claim: later start may help; evidence: attendance/tardiness/sleep; limitation: only two schools.',[
('Claim: sports should end; evidence: bus costs; limitation: student surveys.','source_mix','Those ideas do not accurately represent Source A.'),('Claim: current schedule works; evidence: family preference; limitation: no attendance data.','wrong_source','That map describes Source B more closely.'),('Claim: all schools must change now; evidence: two-school pilot; limitation: none.','overstatement','Source A recommends more testing and acknowledges the pilot\'s limited size.')],'This map preserves Source A\'s claim, its main evidence, and its stated limitation.','Map claim, evidence, and limitation separately.'),
('W1.2','writing.er.map','Which note best maps Source B?','Claim: keep the current schedule for now; reasons: transport/family/activities; limitation: no cost or attendance data.',[
('Claim: later start improved attendance; evidence: 28 percent fewer tardies.','wrong_source','Those details come from Source A.'),('Claim: sports are more important than sleep; evidence: student surveys.','distortion','Source B raises scheduling concerns but does not make this claim.'),('Claim: later starts always fail; evidence: transportation records.','unsupported','Source B does not provide transportation records or claim universal failure.')],'The map captures Source B\'s recommendation and the kinds of support it uses while noting missing evidence.','Do not invent evidence that the source never provides.'),
('W1.1','writing.er.task','Which response plan would best fit this task?','Compare the quality of both arguments, choose one as better supported, and explain why with source evidence.',[
('Describe your own school schedule and whether you like it.','personal_experience','Personal experience does not evaluate the supplied arguments.'),('List every statistic from Source A and stop.','evidence_dump','Evidence needs analysis and comparison, not a list.'),('Explain only why Source B has concerns.','one_source_only','A strong ER response evaluates both sources and makes a judgment.')],'A useful plan includes judgment, evidence, analysis, and comparison.','Plan the reasoning before drafting sentences.'),
('W1.2','writing.er.map','Which detail is a limitation acknowledged by Source A?','The pilot included only two schools.',[
('Attendance improved from 91 to 94 percent.','evidence_not_limit','That is supporting evidence, not a limitation.'),('Families value predictable schedules.','wrong_source','That idea belongs to Source B.'),('Later dismissal could affect sports.','wrong_source','That concern is raised by Source B, not acknowledged by Source A.')],'Source A explicitly limits how broadly the pilot results can be generalized.','A limitation narrows how confidently evidence can be used.'),
('W1.1','writing.er.task','Which statement would be off-task in an ER response?','I prefer later mornings because I personally dislike waking up early.',[
('Source A provides measured changes from a pilot.','on_task','That evaluates source support.'),('Source B raises scheduling concerns but supplies no cost estimates.','on_task','That evaluates a weakness in Source B\'s support.'),('Source A is better supported because it combines results with a stated limitation.','on_task','That directly answers the evaluative task.')],'Personal preference does not show which source is better supported.','If a sentence could be written without reading the sources, question whether it belongs.'),
('W1.2','writing.er.map','Which relationship between the sources is most accurate?','Source A supplies pilot results; Source B mainly raises possible consequences that should be studied.',[
('Both sources use the same attendance study to reach opposite conclusions.','false_equivalence','Source B does not use the attendance study.'),('Source B provides stronger numerical evidence than Source A.','reversal','Source B provides no comparable numerical evidence.'),('Both sources agree that the schedule should change immediately.','unsupported','They recommend different actions.')],'The sources differ mainly in the kind and strength of support they provide.','Map not only what each source says, but how each supports it.'),
('W1.1','writing.er.task','Before choosing a side, what should the learner do first?','Identify each source\'s claim, evidence, reasoning, and limitations.',[
('Write the introduction immediately so time is not wasted.','rushed_drafting','Drafting before mapping increases the chance of source drift.'),('Count which source has more paragraphs.','irrelevant_measure','Length does not determine argument quality.'),('Choose the opinion that sounds more familiar.','personal_bias','Familiarity is not evidence quality.')],'A quick source map gives the learner the information needed for an evidence-based judgment.','Map first; judge second; draft third.')
],
'choose-stronger-argument':[
('W1.3','writing.er.stronger','Which source is better supported overall?','Source A, because it provides pilot use, waste-reduction, and cost data while acknowledging the need to track winter use.',[
('Source B, because it says the city has other needs.','unsupported_reason','A general statement about other needs is not comparative evidence about the refill program.'),('Source B, because it predicts vandalism.','unsupported_prediction','The possibility is not supported with repair records or pilot incidents.'),('Both are equally supported because both express a position.','false_equivalence','Having a position is not the same as supporting it with relevant evidence.')],'Source A combines measured pilot outcomes, a cost estimate, and a limited expansion recommendation.','Compare support, not confidence of tone.'),
('W1.3','writing.er.stronger','What gives Source A its strongest advantage?','It connects its recommendation to measured results from the actual pilot.',[
('It uses more forceful language.','tone_not_evidence','Forceful wording does not strengthen evidence.'),('It promises that plastic waste will disappear.','overstatement','Source A does not make that promise.'),('It ignores maintenance costs.','reversal','Source A provides an annual maintenance estimate.')],'Evidence from the program being evaluated is directly relevant to whether expansion is reasonable.','Ask whether the evidence measures the outcome being claimed.'),
('W1.3','writing.er.stronger','Which weakness most reduces Source B\'s support?','It predicts damage and poor value without pilot repair data or a budget comparison.',[
('It mentions that bottled water still exists.','true_but_weak','That fact does not by itself show the program failed or should not expand.'),('It is written by a neighborhood association.','source_label_only','The author\'s identity alone does not make the argument weak.'),('It disagrees with Source A.','disagreement_not_flaw','Disagreement is not a reasoning flaw by itself.')],'Source B raises possible concerns but does not show that those concerns occurred or outweigh measured benefits.','Name the missing support, not merely that you disagree.'),
('W1.3','writing.er.stronger','Which comparison is most accurate?','Source A uses observed outcomes and cost information; Source B relies more on possibilities and general concerns.',[
('Source A is factual while Source B contains no facts at all.','overstatement','Source B contains some factual statements, but they are less useful to its recommendation.'),('Source B uses the stronger experiment because it discusses vandalism.','unsupported','No vandalism experiment is described.'),('Both sources use identical evidence but interpret it differently.','false_equivalence','The sources rely on different kinds of support.')],'The best comparison identifies the type and quality of support in each source.','Compare evidence quality directly.'),
('W1.3','writing.er.stronger','Which new evidence would most strengthen Source B?','Repair records showing frequent costly damage to the pilot stations.',[
('A resident saying bottled water tastes better.','anecdote','A preference anecdote does not test the vandalism/cost concern.'),('A list of other city programs.','irrelevant','A list does not show the refill program is poor value.'),('A photograph of one refill station.','weak_evidence','A photograph does not establish repair frequency or cost.')],'Repair records would directly test one of Source B\'s central concerns.','The strongest added evidence targets the argument\'s actual claim.'),
('W1.3','writing.er.stronger','Why does Source A\'s limitation improve rather than destroy the argument?','It shows the author recognizes uncertainty and proposes measured expansion instead of claiming the pilot proves everything.',[
('Any limitation automatically proves the argument is wrong.','misconception','Acknowledging a limitation can make reasoning more credible.'),('The limitation guarantees winter use will be high.','unsupported','Tracking winter use means that outcome is still uncertain.'),('The limitation makes the cost estimate irrelevant.','unrelated','The winter-use limitation does not erase maintenance cost information.')],'A qualified conclusion can be stronger because it matches the actual scope of the evidence.','Good arguments often state what the evidence cannot yet show.'),
('W1.3','writing.er.stronger','Which statement is the fairest judgment of Source B?','It raises legitimate questions, but it does not provide enough evidence to show those concerns outweigh the pilot results.',[
('It is useless because it has no numbers.','too_absolute','Arguments can use non-numerical evidence; the problem is insufficient support for its claims.'),('It proves expansion will fail.','overstatement','Its concerns are predictions, not proof.'),('It is stronger because cautious arguments are always better.','rule_error','Caution alone does not determine support quality.')],'A fair evaluation recognizes reasonable concerns while judging whether they are supported.','Do not turn evaluation into ridicule.'),
('W1.3','writing.er.stronger','What should determine the learner\'s final choice?','Which source has the more relevant, sufficient, and well-reasoned support for its recommendation.',[
('Which recommendation would cost less in the learner\'s hometown.','personal_context','The ER uses the supplied sources, not outside assumptions.'),('Which source is shorter.','irrelevant_measure','Length does not determine support.'),('Which source agrees with the learner\'s values.','personal_bias','Personal agreement is not the scoring target.')],'The decision should come from the evidence and reasoning within the paired sources.','Use a consistent support test on both sources.')
],
'thesis-evidence':[
('W1.4','writing.er.thesis','Which thesis is strongest?','Source A presents the better-supported argument because it uses measured pilot results and addresses a communication weakness with a specific safeguard.',[
('Remote work is obviously the future and everyone should support it.','personal_overstatement','This is opinion-based and does not evaluate the source support.'),('Both sources discuss remote work in different ways.','non_evaluative','This does not judge which argument is better supported.'),('Source B is wrong because working from home is convenient.','personal_reason','Convenience is not the source-based reason the task requires.')],'The thesis makes a clear evaluative judgment and previews the evidence/reasoning behind it.','Name the stronger source and the main reasons it is stronger.'),
('W1.5','writing.er.evidence','Which evidence best supports a claim that Source A measures productivity?','Completed projects increased by 12 percent during the six-month pilot.',[
('Seventy-eight percent preferred the schedule.','different_outcome','Preference evidence measures employee response, not productivity.'),('Managers reported communication delays.','limitation_not_support','That is a limitation, not evidence of increased productivity.'),('The company may expand the policy.','recommendation','A recommendation is not measured productivity evidence.')],'Project completion directly measures work output during the policy trial.','Match the evidence to the exact claim you are making.'),
('W1.5','writing.er.evidence','Which evidence best supports a claim about employee acceptance?','Seventy-eight percent of participants preferred the flexible schedule.',[
('Completed projects rose 12 percent.','different_outcome','That measures productivity rather than employee preference.'),('Some managers had communication delays.','different_outcome','That measures a management challenge.'),('Source B predicts distraction.','opposing_claim','That is an unsupported prediction from the other source.')],'The survey directly measures how participants responded to the schedule.','Do not use one statistic to prove a different claim.'),
('W1.4','writing.er.thesis','Which thesis is too strong for the evidence?','Source A proves that remote work always improves every employee\'s performance.',[
('Source A is better supported because it reports pilot outcomes and proposes a response to communication problems.','supported','This stays within the evidence.'),('Source B raises concerns, but its prediction of decline is not supported with pilot productivity data.','supported','This accurately evaluates a weakness.'),('Source A provides stronger support, although the pilot does not show that every department will respond the same way.','qualified','This preserves uncertainty.')],'The pilot supports a limited conclusion; it does not prove a universal result for every employee or setting.','Preserve qualifiers and scope.'),
('W1.5','writing.er.evidence','Which evidence would be weakest in a body paragraph about performance?','The majority of participants preferred the flexible schedule.',[
('Completed projects rose 12 percent.','strong','This is direct performance evidence.'),('Average sick days decreased during the pilot.','relevant','This is a work-outcome measure, though less direct than project completion.'),('Source B provides no pilot performance data for its predicted decline.','comparison','This directly supports a comparison of evidentiary strength.')],'Preference can matter, but it does not directly establish improved performance.','Use the most claim-matched evidence first.'),
('W1.4','writing.er.thesis','Which thesis best preserves the source qualifier?','Source A offers stronger support for expanding remote work with safeguards, not for assuming the policy will work identically in every department.',[
('Source A proves remote work should permanently replace offices.','overstatement','The source recommends expansion with shared office days, not total replacement.'),('Remote work might be good, or it might be bad.','vague','The thesis avoids making the required evaluative judgment.'),('Source B is completely false because it has no statistics.','too_absolute','Lack of data weakens support but does not make every concern false.')],'The thesis makes a judgment while keeping the recommendation limited and conditional.','Strong ER writing can be decisive without becoming absolute.'),
('W1.5','writing.er.evidence','Which quotation would be most useful if the paragraph argues that Source A responds to a weakness?','The company recommends manager training and two shared office days before expansion.',[
('Completed projects increased 12 percent.','different_purpose','That supports productivity, not the response to communication weakness.'),('Remote work is a bad idea for the company.','opposing_claim','That is Source B\'s claim, not Source A\'s response.'),('Employees may become distracted.','unsupported_prediction','That is an unsupported concern from Source B.')],'The recommendation directly responds to the communication problem Source A acknowledges.','Choose evidence that performs the job your sentence claims it performs.'),
('W1.4','writing.er.thesis','What should a high-quality ER thesis avoid?','Reasons that come from personal experience instead of the supplied sources.',[
('Naming the stronger argument.','needed','A clear judgment is useful.'),('Previewing two reasons for the judgment.','needed','This helps organize the response.'),('Using precise words such as better supported.','useful','Precise evaluative language fits the task.')],'A source-based thesis should be grounded in the provided arguments, not outside preference.','If the thesis could be written without reading the sources, revise it.')
],
'analyze-not-summarize':[
('W1.6','writing.er.analysis','Which sentence is analysis rather than summary?','Because the temperature comparison measures the exact outcome Source A discusses, it gives direct support for testing tree shade on another block.',[
('Source A says tree-covered blocks were cooler.','summary','This restates the source without explaining why the evidence matters.'),('The researchers studied eight commercial blocks.','detail_only','This reports a detail but does not analyze its value.'),('Source B says shade sails provide immediate cover.','summary','This repeats Source B\'s claim without evaluating it.')],'Analysis explains the connection between evidence and the argument being evaluated.','After evidence, answer: Why does this make the argument stronger or weaker?'),
('W1.7','writing.er.reasoning','What reasoning weakness is most important in Source B?','It generalizes from one cafe patio to the entire commercial district without broader comparison data.',[
('It mentions that trees grow slowly.','relevant_point','That is a relevant consideration, not automatically a flaw.'),('It prefers shade sails.','position_not_flaw','Having a position is not a reasoning error.'),('It uses the word immediate.','word_choice','The central issue is the scope of its evidence, not that word.')],'The conclusion covers a whole district, but the evidence comes from one patio and lacks cost comparison.','Check whether the conclusion is broader than the evidence.'),
('W1.6','writing.er.analysis','Which sentence best analyzes Source A\'s limitation?','By noting that pavement and building height also affect temperature, Source A avoids treating tree cover as the only possible cause.',[
('Source A mentions buildings and pavement.','summary','This identifies the limitation but does not explain its reasoning value.'),('Trees are always the best way to cool streets.','overstatement','The source does not establish that universal claim.'),('The limitation proves tree planting will fail.','reversal','Acknowledging other factors does not erase the observed temperature pattern.')],'The analysis explains how the limitation makes the reasoning more careful.','A limitation can strengthen credibility when it matches the evidence.'),
('W1.7','writing.er.reasoning','Which comparison sentence is strongest?','Source A recommends a monitored pilot after multi-block measurements, while Source B recommends district-wide adoption from one patio example.',[
('Source A talks about trees, but Source B talks about sails.','topic_only','This compares topics rather than reasoning quality.'),('Source B is shorter and therefore less reliable.','irrelevant_measure','Length is not evidence quality.'),('Both sources want shade, so they are equally strong.','false_equivalence','Agreement on a goal does not make their support equally strong.')],'The sentence directly compares the scale of evidence with the scale of each recommendation.','Compare how the reasoning works, not just what each source prefers.'),
('W1.6','writing.er.analysis','Which follow-up best develops the evidence "tree-covered blocks averaged 5 degrees cooler"?','This matters because it provides a measured comparison across several blocks rather than relying on a single impression of comfort.',[
('Five degrees is a number from Source A.','empty_comment','Naming that it is a number does not analyze its value.'),('Trees have leaves that create shade.','outside_generalization','That may be true, but it does not evaluate the source evidence.'),('Source B prefers sails instead.','topic_shift','This does not explain why the temperature evidence matters.')],'The explanation identifies why the evidence is relevant and comparatively stronger.','Explain the evidentiary value, not merely the content.'),
('W1.7','writing.er.reasoning','Which assumption does Source B make?','A result from one cafe patio is representative enough to justify sails across the district.',[
('Trees take time to mature.','stated_reason','That is stated, not hidden.'),('The city wants cooler commercial areas.','shared_goal','Both sources address that goal.'),('Researchers measured eight blocks.','source_a_fact','That is a Source A detail, not Source B\'s assumption.')],'Source B moves from one location to a district-wide recommendation without showing the example is representative.','Ask what must be true for the conclusion to follow.'),
('W1.6','writing.er.analysis','Which sentence would be too summary-heavy for a body paragraph?','Source A measured eight blocks and Source B discussed one cafe patio.',[
('The broader measurements make Source A more persuasive because they reduce reliance on a single location.','analysis','This explains why the evidence scope matters.'),('Source B\'s one-patio example is relevant but insufficient for its district-wide conclusion.','analysis','This evaluates sufficiency.'),('Source A\'s cautious pilot recommendation better matches the limits of its evidence.','analysis','This evaluates the relationship between evidence and recommendation.')],'The sentence reports facts but does not explain their significance.','Summary tells what; analysis explains why it matters.'),
('W1.7','writing.er.reasoning','Which evaluation is most balanced?','Source B identifies a real speed advantage, but its evidence is too narrow to support choosing sails for the entire district.',[
('Source B has no useful point at all.','too_absolute','Immediate shade is a relevant advantage even if support is incomplete.'),('Source B is automatically stronger because its solution works faster.','single_factor','Speed alone does not establish overall argument strength.'),('Source A proves trees are always cheaper.','unsupported','Source A does not provide a cost comparison.')],'A strong evaluation can recognize a valid point while still explaining why the support is insufficient.','Fair evaluation is stronger than dismissal.')
],
'organize-develop-revise':[
('W1.8','writing.er.organization','Which order best organizes a body paragraph?','Point -> Evidence -> Analysis -> Comparison.',[
('Evidence -> unrelated opinion -> conclusion -> new topic.','disorganized','The sequence does not develop one clear reason.'),('Conclusion -> introduction -> evidence -> title.','wrong_structure','This order does not match paragraph logic.'),('Quotation -> quotation -> quotation -> final sentence.','evidence_dump','Evidence without analysis is not developed argumentation.')],'A clear paragraph states the reason, supports it, explains it, and compares the weaker source when useful.','One paragraph should do one main reasoning job.'),
('W1.9','writing.er.development','Which sentence best develops the Sunday-visit statistic?','Because many Sunday visitors report weekday schedule conflicts, the usage data supports the claim that Sunday hours serve people who have limited access at other times.',[
('There were 310 visitors.','summary','This repeats the number without explaining its significance.'),('Libraries are important to communities.','generic','This broad statement does not develop the source-specific argument.'),('Sunday is the last day of the weekend.','irrelevant','This does not connect the evidence to the recommendation.')],'Development connects the evidence to the claim it helps support.','After a statistic, explain what it demonstrates.'),
('W1.10','writing.er.revision','Which revision is more precise?','Source B raises a cost concern, but it does not compare Sunday staffing with the proposed weekday shift reduction.',[
('Source B is bad and does not make sense.','vague_judgment','This gives no specific reasoning problem.'),('Source B has some things that are not as good.','vague','The reader cannot tell what is weak.'),('Source B is wrong about everything.','overstatement','The evaluation is absolute and unsupported.')],'The revision names the exact missing comparison that weakens the argument.','Replace vague judgment words with the actual reasoning problem.'),
('W1.11','writing.er.edit','Which sentence has the clearest Standard English control?','Although Source B raises a budget concern, it does not compare the proposed schedule changes.',[
('Although Source B raise a budget concern, it do not compare the proposed schedule changes.','agreement','Raise/do do not agree with the singular subject Source B/it.'),('Although Source B raises a budget concern it does not compare, the proposed schedule changes.','punctuation','The comma is misplaced and the introductory clause needs a boundary.'),('Source B raising a budget concern, not compare the proposed schedule changes.','fragment','The sentence lacks a complete finite-verb structure.')],'The sentence uses correct agreement and a clear introductory-clause comma.','Edit for clarity, not decorative complexity.'),
('W1.8','writing.er.organization','Which introduction is most efficient?','Both sources address Sunday library hours, but Source A is better supported because it uses pilot attendance data and addresses cost with a specific schedule tradeoff.',[
('Libraries have existed for many years and are important places for books.','broad_hook','This delays the source-based judgment.'),('In this essay I will talk about two sources and some facts.','meta','This announces writing instead of making an argument.'),('Sunday is one day of the week, and people have different opinions.','empty_background','This adds no useful source analysis.')],'The introduction identifies the issue, makes a judgment, and previews the reasons without wasting time.','In ER, clarity beats a dramatic hook.'),
('W1.9','writing.er.development','Which paragraph plan is most developed?','Reason: access need -> Sunday visitor survey -> explain why it shows unmet weekday access -> compare Source B\'s unsupported assumption that residents can simply reschedule.',[
('Reason: libraries are good -> personal story -> repeat thesis.','outside_support','The plan relies on personal material instead of source evidence.'),('Quote three Source A sentences -> move to conclusion.','evidence_dump','The plan lacks explanation and comparison.'),('Describe Source B -> describe Source A -> stop.','summary_only','The plan summarizes instead of developing evaluation.')],'The plan links a reason to evidence, explanation, and comparison.','Development is a chain, not a pile of details.'),
('W1.10','writing.er.revision','Which revision removes repetition without losing meaning?','Source A is stronger because its pilot data measures actual Sunday use.',[
('Source A is stronger and better and more supported because the data is stronger and better.','repetitive','The sentence repeats evaluative words without adding information.'),('Source A is the source that is stronger because it is the stronger source.','circular','This restates the conclusion instead of giving a reason.'),('Source A, being stronger in strength, has support that supports it.','wordy','The wording is inflated and unclear.')],'The revision states one precise reason once.','Cut repeated evaluation words; keep the evidence-based reason.'),
('W1.11','writing.er.edit','Which edit is best?','Source A acknowledges the staffing cost; however, it proposes reducing a lightly used weekday shift.',[
('Source A acknowledges the staffing cost however it proposes reducing a lightly used weekday shift.','run_on','The conjunctive adverb needs proper punctuation between independent clauses.'),('Source A acknowledge the staffing cost; however, it propose reducing a lightly used weekday shift.','agreement','The verbs do not agree with the singular subject.'),('Source A acknowledges the staffing cost, however; it proposes reducing a lightly used weekday shift.','punctuation','The comma and semicolon are reversed.')],'The semicolon and comma correctly frame however between two independent clauses.','Use punctuation to show the relationship clearly.'),
('W1.8','writing.er.organization','What belongs in the conclusion?','A concise restatement of which argument is better supported and the main reason why.',[
('A new statistic not discussed in the body.','new_evidence','The conclusion should not introduce major new support.'),('A personal story about using a library.','off_task','Personal experience does not improve source evaluation.'),('A sentence apologizing for grammar mistakes.','meta','This does not contribute to the argument.')],'A concise conclusion closes the evaluation without starting a new line of reasoning.','Do not save important analysis for the final sentence.')
],
'full-extended-response':[
('W1.12','writing.er.full_process','Which sequence best fits a 45-minute ER workflow?','Read/map -> choose stronger argument -> outline -> draft -> revise/edit.',[
('Draft immediately -> choose a source later -> skip revision.','rushed','This increases source drift and leaves no quality-control time.'),('Write the conclusion first -> search for evidence -> decide the task.','backward','The judgment should come from source analysis before drafting.'),('Count words -> copy evidence -> add personal opinion -> submit.','off_task','Word count and copied evidence do not replace analysis.')],'The workflow protects time for source analysis, planning, drafting, and revision.','A short plan usually saves time during drafting.'),
('W1.12','writing.er.full_process','Which planner entry is strongest?','Winner: A; Reason 1: measured landfill reduction; Evidence: 19% less trash; B weakness: concerns lack pilot data.',[
('Winner: A; Reason: I like recycling.','personal','Personal preference is not a source-based reason.'),('Winner: B; Reason: B sounds cautious.','tone_only','Caution in tone is not enough to establish stronger support.'),('Winner: A; Evidence: the city has apartments.','weak_evidence','That fact does not support the recommendation.')],'The planner connects the judgment to specific evidence and a comparative weakness.','Use shorthand that preserves the logic you will write later.'),
('W1.12','writing.er.full_process','What should happen when the timer reaches zero in a true simulation?','Editing should stop if the learner was clearly warned before starting, and the response should move to review.',[
('The essay should be automatically scored 6/6 if it is long enough.','fake_scoring','Length cannot establish rubric quality and V1 does not machine-grade essays.'),('The timer should secretly add five minutes.','invalid_simulation','A hidden extension makes timing meaningless.'),('The page should erase the draft.','data_loss','The learner needs the response for review and revision.')],'A simulation needs predictable timing behavior and must preserve the learner\'s work for review.','Clear rules make timed practice useful.'),
('W1.12','writing.er.full_process','Which post-submit label is appropriate for V1?','Self-review: Argument & Evidence - choose 0, 1, or 2 using the rubric checklist.',[
('Official GED Score: 2/2.','misleading','Studo cannot claim an official score.'),('AI-certified Trait Score: 2/2.','misleading','V1 does not use reliable automatic essay grading.'),('Guaranteed exam score: full marks.','misleading','Practice cannot guarantee an official result.')],'The learner may assign a provisional score using transparent criteria, clearly labeled as self-review.','Separate self-review from machine-verified quiz accuracy.'),
('W1.12','writing.er.full_process','When should the model response appear?','After submission, or after the learner explicitly chooses to reveal it.',[
('Before the learner reads the sources.','spoiler','Early exposure turns practice into copying.'),('While the learner is drafting each sentence.','interruptive','Real-time model comparison interferes with independent practice.'),('Only after the learner deletes the draft.','unnecessary','The learner should keep the draft for comparison and revision.')],'Delayed reveal protects independent practice while still supporting learning afterward.','Attempt first; compare second.'),
('W1.12','writing.er.full_process','Which saved information should remain separate from objective mastery?','The learner\'s provisional 0-2 rubric self-scores.',[
('Correct answers on focused W1 quizzes.','objective','Those are objective practice results and can contribute to mastery.'),('Wrong-answer history on objective questions.','objective','That is part of the normal learning signal.'),('Question-family accuracy from selected-response practice.','objective','That comes from machine-verifiable responses.')],'Self-scores are reflective judgments, not verified correctness data.','Label subjective and objective progress separately.'),
('W1.12','writing.er.full_process','Which revision question is most useful after submission?','Where did I explain why the evidence makes one argument stronger, instead of only repeating what the source said?',[
('Did I use the longest words possible?','style_misconception','Complex vocabulary is not the goal.'),('Did I make both sources sound equally strong?','wrong_goal','The task requires an evaluative judgment when support differs.'),('Did I avoid every short sentence?','style_misconception','Sentence length variety matters less than clarity and control.')],'This question targets the common summary-versus-analysis weakness that affects argument/evidence scoring.','Revision questions should point to observable reasoning.'),
('W1.12','writing.er.full_process','What makes an untimed ER attempt different from a timed simulation?','Untimed practice keeps the same source-based task and rubric but removes the countdown so the learner can focus on process.',[
('Untimed practice allows personal opinion instead of evidence.','task_change','The task remains source-based.'),('Untimed practice can reveal the model before writing.','spoiler','Independent attempt should still come first.'),('Untimed practice receives an official score while timed practice does not.','misleading','Neither mode receives an official automatic score.')],'Untimed mode changes pacing support, not the intellectual task or review standard.','Learn the process untimed before adding time pressure.')
]
}


def passage(u):
 return {
  'schemaVersion':2,'id':f"p-rla-er-focus-{u['slug']}",'title':u['passage_title'],'text':u['text'],'textType':'informational','context':u['context'],
  'source':{'type':'original','attribution':'Original content by Studo'},'rights':{'status':'original','holder':'Studo','note':'Original ER component-practice material created for Studo.'},
  'status':'published','version':1,'author':'Studo','reviewer':'Extended Response V1 editorial review'
 }

def make_options(correct_letter, correct_text, wrongs):
 letters='abcd'; data=[]; wi=iter(wrongs)
 for letter in letters:
  if letter==correct_letter: data.append({'id':letter,'text':correct_text})
  else:
   text,typ,why=next(wi); data.append({'id':letter,'text':text,'distractorType':typ,'whyWrong':why})
 return data

def qobj(i, row, letter):
 skill,family,prompt,correct,wrongs,why,tip=row
 return {'id':f'q{i}','type':'multiple_choice','prompt':prompt,'primarySkillId':skill,'familyId':family,'difficulty':'medium' if skill!='W1.12' else 'hard','dok':2 if skill not in ('W1.7','W1.12') else 3,
 'difficultyProfile':{'textComplexity':2,'reasoningDepth':3 if skill in ('W1.7','W1.12') else 2,'evidenceDistance':2,'distractorSimilarity':3,'sourceCount':2,'responseDemand':1},'points':1,'estimatedSeconds':70,
 'options':make_options(letter,correct,wrongs),'correct':letter,'explanation':{'answer':letter.upper(),'whyCorrect':why,'quickTip':tip}}

def setobj(u):
 seq=sequences[u['slug']]
 qs=[qobj(i,row,seq[i-1]) for i,row in enumerate(Q[u['slug']],1)]
 return {'schemaVersion':2,'id':f"set-rla-er-focus-{u['slug']}",'runtime':{'id':f"rla-er-focus-{u['slug']}",'file':f"rla-er-focus-{u['slug']}.json"},
 'title':u['title'],'description':'Focused Extended Response component practice.','subject':'rla','category':'writing','topic':'Extended Response - Focused Practice','difficulty':'medium','status':'published','version':1,
 'passageRefs':[f"p-rla-er-focus-{u['slug']}"],'author':'Studo','reviewer':'Extended Response V1 editorial review','reviewNotes':'Reviewed for source fidelity, one-best-answer logic, close distractors, and rubric-aligned reasoning.',
 'questions':qs,'curriculum':{'domain':'Extended Response','primarySkillId':u['skills'][0],'secondarySkillIds':u['skills'][1:],'unitId':u['id'],'contentKind':'skill_drill','learningObjective':u['title'],'topicLabel':'Extended Response'}}

Q['organize-develop-revise'] = Q['organize-develop-revise'][:8]

for u in units:
 (PASS/f"p-rla-er-focus-{u['slug']}.json").write_text(json.dumps(passage(u),indent=2,ensure_ascii=False)+'\n')
 (SETS/f"set-rla-er-focus-{u['slug']}.json").write_text(json.dumps(setobj(u),indent=2,ensure_ascii=False)+'\n')
print('Generated',len(units),'ER focused passages and sets')
