UNITS = [
    {
        'id':'word-choice-standard-usage','slug':'word-choice-standard-usage','title':'Word Choice & Standard Usage','skills':['L1.1','L1.4'],
        'goal':'Choose words and expressions that are grammatically correct, precise in meaning, and appropriate for standard written English.',
        'explain':'Editing questions often place two words or expressions close together because they sound similar or are common in speech. Your job is not to choose what sounds familiar. Check the word\'s grammatical job, its meaning in the sentence, and whether the expression is standard in formal writing.',
        'contrast':'Do not confuse everyday speech with standard written usage. A phrase can be common in conversation and still be wrong for an editing question. Also separate meaning from spelling: affect/effect, advice/advise, accept/except, and their/there/they\'re do different jobs.',
        'wording':'Questions may ask you to choose the correct word, replace an informal expression, or select the revision that is most appropriate for a formal notice, report, or workplace message.',
        'method':['Identify the job of the missing or underlined word.','State the intended meaning in simple words.','Test the choices one at a time in the sentence.','Reject choices that change the meaning or use the wrong grammatical form.','Reread the complete sentence for standard, natural written English.'],
        'example_text':'The new reminder may affect how many patients arrive on time. The clinic will measure the effect after eight weeks.',
        'example_q':'Why are affect and effect different here?',
        'example_reason':'In the first sentence, the word names an action, so the verb affect is needed. In the second, the word names a result, so the noun effect is needed.',
        'example_answer':'Use affect for the action and effect for the result in these sentences.',
        'traps':['Choosing a word because it sounds similar to the correct one.','Keeping conversational forms such as should of or gotta in formal writing.','Changing a sentence to a different meaning while fixing one word.'],
        'diagnostic':['If you keep missing confused words, label each choice as noun, verb, adjective, or other job before deciding.','If an informal phrase looks tempting, ask how you would write it in a school or workplace report.','If two choices seem possible, substitute each one and explain the exact meaning it creates.'],
        'quick_text':'The supervisor gave the team useful advice and advised them to test the new form for one week.',
        'quick_q':'Which word is the noun, and which is the verb?',
        'quick_answer':'Advice is the noun; advised is the verb.',
        'er_note':'Precise word choice helps your ER analysis say exactly what a source claims. Standard usage also keeps grammar errors from distracting the reader.',
        'wb1':[
            {'text':'All volunteers are welcome {{blank}} those assigned to the closed storage room.','task':'Choose accept or except.','choices':['accept','except','accepted','accepting'],'answer':'B. except','why':'Except means excluding. Accept means receive or agree to.'},
            {'text':'The schedule change may {{blank}} attendance on Monday.','task':'Choose the correct word.','choices':['effect','affect','effects','affection'],'answer':'B. affect','why':'The sentence needs a verb meaning influence, so affect is correct.'},
            {'text':'The coordinator gave us helpful {{blank}} about the new check-in process.','task':'Choose advice or advise.','choices':['advise','advice','advised','advising'],'answer':'B. advice','why':'The sentence needs a noun after helpful; advice is the noun.'},
            {'text':'The workers should of checked the form before leaving.','task':'Choose the standard revision.','choices':['The workers should have checked the form before leaving.','The workers should of checked the form before leaving.','The workers should checked the form before leaving.','The workers should having checked the form before leaving.'],'answer':'A. The workers should have checked the form before leaving.','why':'The standard modal-perfect construction is should have + past participle.'},
        ],
        'wb2':[
            {'text':'The main {{blank}} behind the policy is to protect confidential information.','task':'Choose principle or principal.','choices':['principal','principle','principally','principles'],'answer':'B. principle','why':'Principle means a rule or guiding idea. Principal usually means main or a person in charge.'},
            {'text':'The revised route is shorter {{blank}} the original route.','task':'Choose than or then.','choices':['then','than','that','there'],'answer':'B. than','why':'Than introduces a comparison; then usually refers to time or sequence.'},
            {'text':'The notice says, “You gotta bring your ID if you wanna enter the lab.”','task':'Choose the best formal revision.','choices':['You must bring identification to enter the lab.','You gotta bring your ID to enter the lab.','You wanna bring identification for entering.','Identification, you must gotta bring it.'],'answer':'A. You must bring identification to enter the lab.','why':'It preserves the requirement while using concise standard written English.'},
            {'text':'The audit found {{blank}} errors after the checklist was introduced.','task':'Choose fewer or less.','choices':['less','fewer','fewest amount of','lesser'],'answer':'B. fewer','why':'Errors are countable plural items, so fewer is the standard choice.'},
        ]
    },
    {
        'id':'agreement-pronouns','slug':'agreement-pronouns','title':'Agreement & Pronouns','skills':['L1.2','L1.3','L1.7'],
        'goal':'Make verbs agree with their true subjects and use pronouns that agree, refer clearly, and take the correct case.',
        'explain':'Long sentences can hide the real subject behind prepositional phrases or extra details. Pronouns can also become unclear when more than one noun could be the antecedent. Strong editing means finding the sentence skeleton first, then checking number, reference, and case.',
        'contrast':'Do not match the verb with the nearest noun unless that noun is actually the subject. In “The list of repairs is posted,” repairs is plural but list is the subject. Also do not keep a pronoun if the reader must guess what it refers to.',
        'wording':'Questions may ask which verb agrees with the subject, which pronoun correctly replaces a noun, or which revision removes an unclear pronoun reference.',
        'method':['Cross out interrupting phrases mentally and find the true subject.','Decide whether that subject is singular or plural.','Check every pronoun for a clear antecedent.','Check pronoun number and case.','Reread the sentence to make sure no pronoun could point to two different nouns.'],
        'example_text':'The list of delayed trucks is updated each afternoon. When supervisors discuss a delay, they record its expected arrival time.',
        'example_q':'Why is is correct in the first sentence?',
        'example_reason':'The subject is list, not trucks. The phrase of delayed trucks only describes the list.',
        'example_answer':'List is singular, so the singular verb is agrees with it.',
        'traps':['Matching the verb to a noun inside an of-phrase.','Using it, they, or this when two different nouns could fit.','Using I or me based only on what sounds formal.'],
        'diagnostic':['If agreement questions feel random, reduce the sentence to subject + verb before choosing.','If you miss pronoun reference, replace the pronoun with the noun you think it means and test whether the sentence stays logical.','If case is difficult, remove the other person: “between I” sounds wrong; “between me” is standard.'],
        'quick_text':'Each of the volunteers has a badge, and all of them keep their badges visible.',
        'quick_q':'Why are has and their both correct?',
        'quick_answer':'Each is singular, so it takes has. Them refers to all volunteers, so the plural possessive their agrees with them.',
        'er_note':'Clear agreement and pronoun reference make complex evidence comparisons easier to follow in an ER.',
        'wb1':[
            {'text':'The list of replacement parts {{blank}} on the desk.','task':'Choose the correct verb.','choices':['are','is','were','have'],'answer':'B. is','why':'List is the singular subject; of replacement parts is only a modifying phrase.'},
            {'text':'Each of the students {{blank}} a copy of the report.','task':'Choose the correct verb.','choices':['have','has','are having','were have'],'answer':'B. has','why':'Each is singular and takes has.'},
            {'text':'The supervisor spoke to Maria and {{blank}} after the meeting.','task':'Choose I or me.','choices':['I','me','myself','mine'],'answer':'B. me','why':'The pronoun is the object of to. “Spoke to me” confirms the correct case.'},
            {'text':'When the manager placed the report beside the schedule, it was outdated.','task':'Choose the clearest revision.','choices':['When the manager placed the outdated report beside the schedule, the report was easy to find.','When the manager placed the report beside the schedule, it was outdated.','When it was placed beside it, it was outdated.','The manager placed it beside the schedule because it was outdated.'],'answer':'A. When the manager placed the outdated report beside the schedule, the report was easy to find.','why':'The revision removes the unclear it by naming which item was outdated.'},
        ],
        'wb2':[
            {'text':'The box of safety forms, along with two clipboards, {{blank}} beside the entrance.','task':'Choose the correct verb.','choices':['sit','sits','have sat','were sitting'],'answer':'B. sits','why':'Box is the subject. Along with two clipboards does not make the subject plural.'},
            {'text':'Neither the assistants nor the manager {{blank}} available after 6 p.m.','task':'Choose the correct verb.','choices':['are','is','were','have been'],'answer':'B. is','why':'With neither...nor, the verb agrees with the nearer subject here: manager, which is singular.'},
            {'text':'The policy was reviewed by Jordan and {{blank}}.','task':'Choose the correct pronoun.','choices':['I','me','my','mine'],'answer':'B. me','why':'The pronoun is an object in the phrase by Jordan and me.'},
            {'text':'The clinic changed the reminder schedule after it received complaints, but this confused some patients.','task':'Choose the clearest revision of this.','choices':['The schedule change confused some patients.','This confused some patients.','It changed this, which confused them.','The clinic changed it after this, and this confused some patients.'],'answer':'A. The schedule change confused some patients.','why':'The noun phrase names exactly what caused the confusion instead of using a vague this.'},
        ]
    },
    {
        'id':'modifiers-sentence-logic','slug':'modifiers-sentence-logic','title':'Modifiers & Sentence Logic','skills':['L1.5'],
        'goal':'Place descriptive and limiting words where they clearly modify the intended person, thing, action, or condition.',
        'explain':'A modifier adds information, but its position controls meaning. Misplaced words such as only, nearly, or almost can change what a sentence claims. Introductory phrases can also dangle if the person doing the action is not named immediately afterward.',
        'contrast':'Compare “Only staff may enter” with “Staff may enter only after 8 a.m.” The same word changes the rule depending on placement. Also compare “After reading the report, Maya revised it” with “After reading the report, the errors were revised.” Only the first names who did the reading.',
        'wording':'Questions may ask for the clearest modifier placement, a revision of a dangling modifier, or a sentence whose word order expresses the intended meaning.',
        'method':['Find the modifier or introductory phrase.','Ask exactly what word or idea it should describe.','Place the modifier next to that target.','Check whether the subject after an introductory phrase actually performed the action.','Reread for unintended meanings created by only, nearly, almost, or similar words.'],
        'example_text':'After reviewing the safety log, the supervisor revised the checklist.',
        'example_q':'Why is the modifier clear?',
        'example_reason':'The phrase “After reviewing the safety log” describes the supervisor, and supervisor appears immediately after the phrase.',
        'example_answer':'The sentence clearly identifies the supervisor as the person who reviewed the log.',
        'traps':['Letting an introductory phrase describe the wrong noun.','Placing only too far from the word or condition it limits.','Choosing a grammatically smooth sentence that changes the intended meaning.'],
        'diagnostic':['If a sentence sounds strange, ask who actually performed the action in the opening phrase.','If only is present, move it mentally and notice how the meaning changes.','If two choices are grammatical, choose the one that places the description closest to its target.'],
        'quick_text':'To reduce delays, the team changed only the morning check-in process.',
        'quick_q':'What does only limit?',
        'quick_answer':'Only limits the morning check-in process; the sentence does not say every process changed.',
        'er_note':'Precise modifier placement prevents your ER from accidentally changing the scope of a source claim.',
        'wb1':[
            {'text':'After reading the instructions, the machine was started by Elena.','task':'Choose the clearest revision.','choices':['After reading the instructions, Elena started the machine.','After reading the instructions, the machine was started by Elena.','Reading the instructions, the machine started Elena.','After the instructions, Elena was machine starting.'],'answer':'A. After reading the instructions, Elena started the machine.','why':'Elena is the person who read the instructions, so her name follows the opening phrase.'},
            {'text':'Riders should only call after they receive a match notice.','task':'Move only to show that the timing, not the action, is limited.','choices':['Only riders should call after they receive a match notice.','Riders should call only after they receive a match notice.','Riders only should call after they receive a match notice.','Riders should call after only they receive a match notice.'],'answer':'B. Riders should call only after they receive a match notice.','why':'Only directly limits the after-clause.'},
            {'text':'The coordinator almost reviewed fifty forms.','task':'Choose the revision meaning that about fifty forms were reviewed.','choices':['The coordinator reviewed almost fifty forms.','The coordinator almost reviewed fifty forms.','Almost the coordinator reviewed fifty forms.','The coordinator reviewed fifty almost forms.'],'answer':'A. The coordinator reviewed almost fifty forms.','why':'Almost directly modifies fifty.'},
            {'text':'Walking through the lobby, the new signs were easy to see.','task':'Choose the logical revision.','choices':['Walking through the lobby, visitors could easily see the new signs.','Walking through the lobby, the new signs were easy to see.','The signs, walking through the lobby, were easy to see.','Walking, the lobby showed signs.'],'answer':'A. Walking through the lobby, visitors could easily see the new signs.','why':'Visitors, not signs, can walk through the lobby.'},
        ],
        'wb2':[
            {'text':'The manager said employees should submit reports only on Friday.','task':'Which meaning does the sentence most clearly express?','choices':['Friday is the only day for submitting reports.','Only employees, not managers, may submit reports.','Employees should submit only reports and nothing else.','The manager speaks only on Friday.'],'answer':'A. Friday is the only day for submitting reports.','why':'Only sits directly before the time phrase on Friday.'},
            {'text':'Using the updated map, the detour was easier for drivers to follow.','task':'Choose the best revision.','choices':['Using the updated map, drivers could follow the detour more easily.','Using the updated map, the detour was easier for drivers to follow.','The map used the drivers to follow the detour.','Using the detour, the map followed the drivers.'],'answer':'A. Using the updated map, drivers could follow the detour more easily.','why':'Drivers are the users of the map, so they must follow the opening phrase.'},
            {'text':'The lab nearly recorded every temperature reading.','task':'Choose the revision meaning all readings were recorded and their values were close to each other.','choices':['The lab recorded nearly every temperature reading.','The lab recorded every temperature reading, and the values were nearly the same.','Nearly the lab recorded every temperature reading.','The lab nearly recorded every temperature reading.'],'answer':'B. The lab recorded every temperature reading, and the values were nearly the same.','why':'The original nearly modifies recorded and suggests the recording almost happened. The revision states the intended two ideas explicitly.'},
            {'text':'Before approving the schedule, the staffing levels were reviewed.','task':'Choose the clearest revision.','choices':['Before approving the schedule, the director reviewed the staffing levels.','Before approving the schedule, the staffing levels were reviewed.','The staffing levels approved the schedule after review.','Before approval, reviewing staffing levels was scheduled.'],'answer':'A. Before approving the schedule, the director reviewed the staffing levels.','why':'The director is now clearly the person who approves and reviews.'},
        ]
    },
    {
        'id':'parallelism-sentence-connections','slug':'parallelism-sentence-connections','title':'Parallelism & Sentence Connections','skills':['L1.6'],
        'goal':'Keep equivalent ideas in the same grammatical form and connect clauses so their logical relationship is clear.',
        'explain':'Parallel structure makes lists and paired ideas easier to follow. Coordination joins ideas of similar importance; subordination shows that one idea depends on or qualifies another. Editing questions often test both form and logic at the same time.',
        'contrast':'“The job requires checking labels, recording counts, and reporting damage” is parallel. “Checking labels, to record counts, and damage reports” is not. Also, and, but, because, although, and while do different logical jobs.',
        'wording':'Questions may ask for the most parallel revision, the best way to combine two sentences, or the conjunction that expresses contrast, cause, addition, or condition.',
        'method':['Identify the items or clauses being connected.','Decide whether they have equal importance or whether one depends on the other.','Put items with the same job into the same grammatical form.','Choose the conjunction that matches the exact relationship.','Read the whole sentence aloud in your head to check balance and logic.'],
        'example_text':'The checklist asks workers to inspect the seal, record the temperature, and report any damage.',
        'example_q':'What makes the list parallel?',
        'example_reason':'All three items begin with base verbs after to is understood: inspect, record, report.',
        'example_answer':'The three actions use the same grammatical pattern.',
        'traps':['Mixing nouns, -ing forms, and infinitives in one list without a reason.','Using and when the sentence needs contrast or cause.','Making one side of a paired construction much longer or structurally different from the other.'],
        'diagnostic':['If a list feels uneven, underline the first word of each item and compare their forms.','If a conjunction question is difficult, name the relationship first: addition, contrast, cause, time, or condition.','If not only/but also appears, check that the structures after both parts match.'],
        'quick_text':'The pilot was inexpensive but difficult to schedule.',
        'quick_q':'What relationship does but express?',
        'quick_answer':'But connects two equally important ideas while signaling contrast.',
        'er_note':'Parallel comparisons help an ER compare two arguments cleanly, and accurate conjunctions show how evidence connects to your reasoning.',
        'wb1':[
            {'text':'The position requires answering calls, updating records, and {{blank}} reports.','task':'Choose the parallel form.','choices':['filing','to file','files','filed'],'answer':'A. filing','why':'All list items use -ing forms: answering, updating, filing.'},
            {'text':'The route is shorter, {{blank}} it requires one transfer.','task':'Choose the conjunction showing contrast.','choices':['and','but','because','so'],'answer':'B. but','why':'The second idea limits the advantage in the first, so contrast is needed.'},
            {'text':'Because the alarm failed. The team repeated the inspection.','task':'Choose the best sentence.','choices':['Because the alarm failed, the team repeated the inspection.','Because the alarm failed. The team repeated the inspection.','The team because the alarm failed repeated.','Because, the alarm failed the team repeated the inspection.'],'answer':'A. Because the alarm failed, the team repeated the inspection.','why':'The dependent because-clause is attached to the complete main clause.'},
            {'text':'The new form is easier to scan and requires less time to complete.','task':'Which relationship does and express?','choices':['addition','contrast','cause','condition'],'answer':'A. addition','why':'The sentence presents two compatible benefits.'},
        ],
        'wb2':[
            {'text':'The policy aims not only to reduce delays but also {{blank}} communication between shifts.','task':'Choose the parallel completion.','choices':['improving','to improve','improved','communication improves'],'answer':'B. to improve','why':'Not only to reduce pairs with but also to improve.'},
            {'text':'The pilot reduced waiting time. It increased staff workload.','task':'Choose the best combined sentence.','choices':['Although the pilot reduced waiting time, it increased staff workload.','Because the pilot reduced waiting time, it increased staff workload.','The pilot reduced waiting time, so it increased staff workload.','The pilot reduced waiting time and therefore workload decreased.'],'answer':'A. Although the pilot reduced waiting time, it increased staff workload.','why':'Although accurately shows the contrast between a benefit and a drawback without inventing causation.'},
            {'text':'The report recommends checking the roof, a review of the drains, and testing the pumps.','task':'Choose the most parallel revision.','choices':['The report recommends checking the roof, reviewing the drains, and testing the pumps.','The report recommends the roof, reviewing drains, and pumps are tested.','The report recommends to check the roof, a review of drains, and testing pumps.','The report recommends checking, the drains, and testing.'],'answer':'A. The report recommends checking the roof, reviewing the drains, and testing the pumps.','why':'All three recommended actions use matching -ing forms.'},
            {'text':'The clinic kept the extra reminder {{blank}} the short pilot did not prove that it caused the improvement.','task':'Choose the connector that preserves the limitation.','choices':['although','because','therefore','for example'],'answer':'A. although','why':'Although shows that the clinic continued despite an important limitation.'},
        ]
    },
    {
        'id':'concision-transitions','slug':'concision-transitions','title':'Concision & Transitions','skills':['L1.8','L1.9'],
        'goal':'Express the same meaning with direct wording and choose transitions that show the exact relationship between ideas.',
        'explain':'Good editing removes words that repeat an idea or hide the main verb. It also uses transitions as logic signals, not decoration. A concise sentence is not merely short; it preserves every important condition, degree of certainty, and relationship.',
        'contrast':'“The committee made a decision to delay” can become “The committee decided to delay.” But deleting “for six weeks” would change useful information. Likewise, however, therefore, for example, and meanwhile are not interchangeable.',
        'wording':'Questions may ask for the most concise revision without changing meaning or the transition that best expresses contrast, cause-result, example, sequence, or addition.',
        'method':['State the sentence\'s essential meaning.','Replace noun-heavy phrases with direct verbs when possible.','Delete repeated words, not necessary limits or conditions.','Name the relationship between sentences before choosing a transition.','Reread to confirm the revision did not make the claim broader or more certain.'],
        'example_text':'The team conducted an evaluation of the new form. The team evaluated the new form.',
        'example_q':'Why is the second sentence stronger?',
        'example_reason':'Evaluated expresses the same action directly. The longer phrase adds no useful meaning.',
        'example_answer':'The second sentence is more concise without losing information.',
        'traps':['Choosing the shortest option even when it deletes an important condition.','Using therefore when the first sentence does not actually cause the second.','Keeping phrases such as in order to, due to the fact that, or made a decision to when simpler wording works.'],
        'diagnostic':['If your revision changes a number, condition, or uncertainty word, you cut too much.','If two transitions seem possible, state the relationship in plain language before selecting one.','If a sentence feels heavy, find the main noun and ask whether it can become the main verb.'],
        'quick_text':'The trial reduced delays. However, staffing costs increased.',
        'quick_q':'Why is however appropriate?',
        'quick_answer':'It signals a contrast between an operational benefit and a cost drawback.',
        'er_note':'Concision gives you more room for analysis in a timed ER, while precise transitions make your reasoning easier to follow.',
        'wb1':[
            {'text':'The manager made a decision to extend the pilot.','task':'Choose the most concise revision.','choices':['The manager decided to extend the pilot.','The manager made a decision to extend the pilot.','The manager came to a decision in regard to extending the pilot.','A decision was made by the manager for extension of the pilot.'],'answer':'A. The manager decided to extend the pilot.','why':'Decided replaces the wordy phrase without changing meaning.'},
            {'text':'The road was flooded. {{blank}}, the bus used a detour.','task':'Choose the best transition.','choices':['Therefore','However','For example','Similarly'],'answer':'A. Therefore','why':'The flooded road caused the detour, so a result transition is appropriate.'},
            {'text':'The report lists three concerns. {{blank}}, it notes that the waiting area has only twelve seats.','task':'Choose the transition introducing an example.','choices':['For example','Therefore','However','Meanwhile'],'answer':'A. For example','why':'The second sentence gives one specific example of a concern.'},
            {'text':'The team repeated the test again a second time.','task':'Choose the concise revision.','choices':['The team repeated the test.','The team repeated the test again a second time.','The team did a repetition of the test again.','Again a second test repetition was done by the team.'],'answer':'A. The team repeated the test.','why':'Repeated already means did again, so again and a second time are redundant.'},
        ],
        'wb2':[
            {'text':'At this point in time, the committee is currently reviewing the proposal.','task':'Choose the best revision.','choices':['The committee is reviewing the proposal.','At this point in time, the committee is currently reviewing the proposal.','Currently at this point, the proposal is in review by the committee.','The committee is currently at this time in the process of reviewing the proposal.'],'answer':'A. The committee is reviewing the proposal.','why':'The present-progressive verb already shows the action is happening now.'},
            {'text':'The first trial reduced errors by 9 percent. {{blank}}, managers say the sample was too small for a firm conclusion.','task':'Choose the best transition.','choices':['However','Therefore','For example','Similarly'],'answer':'A. However','why':'The second sentence limits the encouraging result, so contrast is needed.'},
            {'text':'The notice must remain brief {{blank}} many patients read it on a phone.','task':'Choose the connector expressing reason.','choices':['because','although','meanwhile','for example'],'answer':'A. because','why':'The phone-reading context explains why brevity matters.'},
            {'text':'The form includes a field that is used for the purpose of recording urgent problems.','task':'Choose the concise revision that preserves purpose.','choices':['The form includes a field for urgent problems.','The form records urgent problems only.','Urgent problems are the form.','The form includes a field that is used for the purpose of recording urgent problems.'],'answer':'A. The form includes a field for urgent problems.','why':'The shorter phrase keeps the field\'s purpose without unnecessary wording.'},
        ]
    },
    {
        'id':'sentence-boundaries-punctuation','slug':'sentence-boundaries-punctuation','title':'Sentence Boundaries & Punctuation','skills':['L2.2','L2.4'],
        'goal':'Recognize complete and incomplete clauses and use punctuation to separate, join, or introduce ideas correctly.',
        'explain':'A complete sentence needs an independent clause. Fragments leave a dependent idea unfinished; run-ons join complete clauses without a legal boundary. Punctuation choices depend on clause structure first, not on where you happen to pause while reading.',
        'contrast':'A comma alone cannot normally join two independent clauses. Use a period, semicolon, or comma + coordinating conjunction. A colon can introduce a list or explanation only after a complete clause.',
        'wording':'Questions may ask you to repair a fragment or run-on, choose punctuation between clauses, or insert a colon, comma, semicolon, or apostrophe where structure requires it.',
        'method':['Find the subject and verb in each clause.','Decide whether each clause can stand alone.','If both are independent, use a legal boundary: period, semicolon, or comma + coordinator.','If one clause is dependent, attach it to a complete clause.','Use a colon only when the words before it form a complete clause that introduces what follows.'],
        'example_text':'The pilot ended on Friday; managers reviewed the results on Monday.',
        'example_q':'Why can a semicolon join these parts?',
        'example_reason':'Both sides are independent clauses that could stand as separate sentences, and their ideas are closely related.',
        'example_answer':'A semicolon is a valid boundary between the two complete related clauses.',
        'traps':['Using a comma splice between two complete sentences.','Treating a dependent clause beginning with because, although, or if as a complete sentence.','Putting a colon after a verb or preposition when the preceding words are not a complete clause.'],
        'diagnostic':['If punctuation feels like guessing, mark each clause I for independent or D for dependent first.','If you chose a comma between two I clauses, check whether a coordinating conjunction is also present.','If you chose a colon, read only the words before it and ask whether they form a complete sentence.'],
        'quick_text':'The form asks for three details: the item, the location, and a contact method.',
        'quick_q':'Why is the colon correct?',
        'quick_answer':'The words before the colon form a complete clause and announce the list that follows.',
        'er_note':'Sentence-boundary control is one of the fastest ways to make an ER clearer and easier to score for Standard English.',
        'wb1':[
            {'text':'Because the front entrance was closed.','task':'Choose the complete revision.','choices':['Because the front entrance was closed, visitors used the east door.','Because the front entrance was closed.','The front entrance because closed.','Because closed, the front entrance.'],'answer':'A. Because the front entrance was closed, visitors used the east door.','why':'The dependent because-clause is attached to a complete main clause.'},
            {'text':'The meeting ended late, the last bus had already left.','task':'Choose a correct repair.','choices':['The meeting ended late, so the last bus had already left.','The meeting ended late, the last bus had already left.','The meeting ended late because, the last bus had already left.','The meeting ended late: because the last bus had already left.'],'answer':'A. The meeting ended late, so the last bus had already left.','why':'Comma + so legally joins the two independent clauses and states a result relationship.'},
            {'text':'The checklist covers three areas {{blank}} tools, exits, and protective equipment.','task':'Choose the punctuation.','choices':[':',',',';','.'],'answer':'A. :','why':'A complete clause announces a list, so a colon is appropriate.'},
            {'text':'The pilot was short {{blank}} the results were encouraging.','task':'Choose a valid boundary that keeps the ideas closely connected.','choices':['; ',',',': because','and,'],'answer':'A. ;','why':'Both sides are complete clauses, so a semicolon can join them.'},
        ],
        'wb2':[
            {'text':'Although the software reduced duplicate entries. Managers still found several labeling errors.','task':'Choose the best repair.','choices':['Although the software reduced duplicate entries, managers still found several labeling errors.','Although the software reduced duplicate entries. Managers still found several labeling errors.','The software although reduced duplicate entries, managers still found errors.','Although, the software reduced duplicate entries managers still found errors.'],'answer':'A. Although the software reduced duplicate entries, managers still found several labeling errors.','why':'The dependent although-clause must attach to the main clause.'},
            {'text':'The manager reviewed the log, she called the technician immediately.','task':'Choose the revision that shows two separate complete actions without adding a new logical relationship.','choices':['The manager reviewed the log; she called the technician immediately.','The manager reviewed the log, she called the technician immediately.','The manager reviewed the log: because she called the technician immediately.','The manager reviewed; the log she called the technician immediately.'],'answer':'A. The manager reviewed the log; she called the technician immediately.','why':'A semicolon correctly joins the two closely related independent clauses without inventing cause or contrast.'},
            {'text':'The notice includes {{blank}} a map, a phone number, and office hours.','task':'Should a colon go in the blank?','choices':['No punctuation is needed.','Use a colon.','Use a semicolon.','Use a period.'],'answer':'A. No punctuation is needed.','why':'The words before the blank do not form a complete clause; the verb includes flows directly into its objects.'},
            {'text':'If the alarm sounds, leave the room immediately {{blank}} do not stop to collect personal items.','task':'Choose the punctuation and connector.','choices':[', and',',',';',':'],'answer':'A. , and','why':'The comma + and joins two independent commands with an additive relationship.'},
        ]
    },
    {
        'id':'capitalization-possessives','slug':'capitalization-possessives','title':'Capitalization & Possessives','skills':['L2.1','L2.3'],
        'goal':'Capitalize proper names and formal titles correctly and use apostrophes to show possession or contractions without confusing them with plurals.',
        'explain':'Capitalization marks proper names, calendar names, and certain formal titles. Apostrophes show possession or omitted letters in contractions; they do not make ordinary nouns plural. Possessive pronouns such as its, yours, and theirs do not use apostrophes.',
        'contrast':'Its shows possession; it\'s means it is or it has. Guides is plural; guide\'s means belonging to one guide; guides\' means belonging to multiple guides. Capitalize Monday and September, but not common nouns such as meeting or program unless they are part of a proper name.',
        'wording':'Questions may ask for the correctly capitalized sentence, the correct singular or plural possessive, or the correct form of its/it\'s and similar words.',
        'method':['Decide whether each name is proper or common.','Check whether a title is used as part of a person\'s name or generically.','For apostrophes, decide plural or singular before deciding possession.','Test contractions by expanding them: it\'s -> it is/it has.','Reread the noun phrase to confirm who owns what.'],
        'example_text':'The guides\' schedules were posted on Monday, and the museum updated its website that afternoon.',
        'example_q':'Why do guides\' and its use different forms?',
        'example_reason':'Guides\' is a plural noun showing possession, so it takes an apostrophe after s. Its is a possessive pronoun, so it never takes an apostrophe.',
        'example_answer':'Use guides\' for possession by multiple guides and its for the museum\'s possession.',
        'traps':['Adding apostrophes to ordinary plurals.','Confusing its with it\'s.','Capitalizing common nouns merely because they seem important.'],
        'diagnostic':['If apostrophes are difficult, first write the plain plural or singular noun, then add possession.','If you choose it\'s, expand it to it is. If the sentence breaks, use its.','If capitalization feels uncertain, ask whether the word names one specific official person/place/date or an ordinary category.'],
        'quick_text':'Dr. Maya Chen will speak on Tuesday, and the students\' questions will be collected afterward.',
        'quick_q':'Which words are capitalized or possessive, and why?',
        'quick_answer':'Dr. Maya Chen and Tuesday are proper-name/calendar forms; students\' shows possession by multiple students.',
        'er_note':'Correct mechanics support the Standard English trait in the ER, but clarity and accurate reasoning still matter more than decorative formality.',
        'wb1':[
            {'text':'The meeting is scheduled for {{blank}}.','task':'Choose the correct capitalization.','choices':['monday','Monday','MONday','monday.'],'answer':'B. Monday','why':'Days of the week are proper nouns and are capitalized.'},
            {'text':'The {{blank}} office is beside the entrance.','task':'Choose the singular possessive.','choices':['manager\'s','managers','managers\'','managerss'],'answer':'A. manager\'s','why':'One manager owns or uses the office, so add apostrophe + s.'},
            {'text':'The department updated {{blank}} schedule.','task':'Choose its or it\'s.','choices':['it\'s','its','its\'','it is'],'answer':'B. its','why':'Its is the possessive pronoun. It\'s would expand to it is, which does not fit.'},
            {'text':'The report was released in september.','task':'Choose the correct revision.','choices':['The report was released in September.','The Report was released in september.','The report was released in september.','The report was Released in September.'],'answer':'A. The report was released in September.','why':'The month name is capitalized; ordinary nouns and verbs are not.'},
        ],
        'wb2':[
            {'text':'The two {{blank}} schedules were changed after the meeting.','task':'Choose the plural possessive.','choices':['driver\'s','drivers','drivers\'','drivers\'s'],'answer':'C. drivers\'','why':'The schedules belong to multiple drivers; a regular plural ending in s takes an apostrophe after s.'},
            {'text':'Choose the sentence with correct capitalization.','task':'Assume President Maya Chen is the person\'s official title and name.','choices':['President Maya Chen opened the meeting.','president Maya Chen opened the meeting.','President maya chen opened the meeting.','President Maya Chen opened the Meeting.'],'answer':'A. President Maya Chen opened the meeting.','why':'The formal title immediately before the name and the personal name are capitalized; the common noun meeting is not.'},
            {'text':'The committee changed {{blank}} plan because the original deadline no longer worked.','task':'Choose the possessive form.','choices':['its','it\'s','its\'','it is'],'answer':'A. its','why':'The plan belongs to the committee represented by it; possessive its has no apostrophe.'},
            {'text':'The {{blank}} equipment was stored separately after the event.','task':'Choose the form meaning equipment belonging to several volunteers.','choices':['volunteer\'s','volunteers','volunteers\'','volunteers\'s'],'answer':'C. volunteers\'','why':'Several volunteers is a regular plural ending in s, so possession is shown with an apostrophe after the s.'},
        ]
    },
]
